# --- MANALI (20 Activities) ---
manali_activities = [
    {
        "activity_id": "hadimba_temple_manali_01", "destination": "Manali", "name": "Hadimba Temple Forest Tour",
        "category": "spiritual", "duration_minutes": 60, "cost_per_person": 0,
        "available_slots": ["09:00", "11:00", "14:00", "16:00"], "risk_level": "low",
        "tags": ["spiritual", "temple", "forest", "heritage", "family"], "lat": 32.2464, "lng": 77.1794,
        "fatigue_score_base": 2, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Oct-Jun"], "accessibility": "easy",
        "editorial_summary": "An ancient 16th-century wooden temple with a pagoda-shaped roof, set amidst towering cedar forests.",
        "opening_hours": ["Monday-Sunday: 08:00-18:00"], "skip_if": "Heavy winter blizzards block the narrow forest road access.",
        "insider_tip": "You can pose for photos holding fluffy Angora rabbits and local mountain yaks outside the temple courtyard.",
        "confidence_pct": 99
    },
    {
        "activity_id": "solang_paragliding_manali_02", "destination": "Manali", "name": "Solang Valley Paragliding",
        "category": "adventure", "duration_minutes": 90, "cost_per_person": 3000,
        "available_slots": ["09:00", "11:00", "13:00", "15:00"], "risk_level": "high",
        "tags": ["adventure", "paragliding", "flying", "scenic"], "lat": 32.3168, "lng": 77.1610,
        "fatigue_score_base": 5, "morale_score_base": 10, "best_time_of_day": "morning",
        "best_season": ["Oct-May"], "accessibility": "easy",
        "editorial_summary": "Fly tandem with professional pilots over Solang Valley, enjoying views of snow-capped peaks.",
        "opening_hours": ["Monday-Sunday: 09:00-17:00"], "skip_if": "Strong winds, rainy weather, or foggy visibility.",
        "insider_tip": "Pay extra for the Go-Pro video stick to record your flight; the footage is worth it.",
        "confidence_pct": 92
    },
    {
        "activity_id": "rohtang_pass_manali_03", "destination": "Manali", "name": "Rohtang Pass Snow Excursion",
        "category": "adventure", "duration_minutes": 360, "cost_per_person": 550,
        "available_slots": ["06:00", "07:30"], "risk_level": "high",
        "tags": ["adventure", "pass", "snow", "roadtrip", "scenic"], "lat": 32.3716, "lng": 77.2439,
        "fatigue_score_base": 6, "morale_score_base": 10, "best_time_of_day": "morning",
        "best_season": ["Jun-Oct"], "accessibility": "difficult",
        "editorial_summary": "A high mountain pass connecting Kullu with Lahaul Valley, offering year-round snow landscapes.",
        "opening_hours": ["Monday-Sunday: 24 Hours"], "skip_if": "Tuesdays, when the pass is closed for maintenance. Also check online for permits.",
        "insider_tip": "Rohtang requires a strict vehicle permit. Book it online exactly at 10 AM on the state portal three days prior.",
        "confidence_pct": 98
    },
    {
        "activity_id": "jogini_falls_manali_04", "destination": "Manali", "name": "Jogini Waterfalls Pine Hike",
        "category": "nature", "duration_minutes": 150, "cost_per_person": 0,
        "available_slots": ["08:30", "10:30", "14:00"], "risk_level": "low",
        "tags": ["nature", "waterfall", "hiking", "trekking", "scenic"], "lat": 32.2680, "lng": 77.1950,
        "fatigue_score_base": 5, "morale_score_base": 9, "best_time_of_day": "morning",
        "best_season": ["Oct-Jun"], "accessibility": "moderate",
        "editorial_summary": "A scenic trek from Vashisht village through orchards and pine forests to a cascading waterfall pool.",
        "opening_hours": ["Monday-Sunday: 06:00-18:00"], "skip_if": "Monsoons, when the mud paths are slippery and landslide-prone.",
        "insider_tip": "Stop at the small wooden tea shacks along the trek to drink fresh lemon-honey tea with mountain views.",
        "confidence_pct": 96
    },
    {
        "activity_id": "old_manali_cafes_manali_05", "destination": "Manali", "name": "Old Manali Cafe Hopping",
        "category": "food", "duration_minutes": 120, "cost_per_person": 600,
        "available_slots": ["13:00", "16:00", "18:30", "20:30"], "risk_level": "low",
        "tags": ["food", "cafe", "music", "nightlife", "relaxed"], "lat": 32.2533, "lng": 77.1770,
        "fatigue_score_base": 2, "morale_score_base": 8, "best_time_of_day": "evening",
        "best_season": ["Oct-Jun"], "accessibility": "easy",
        "editorial_summary": "Explore the narrow lanes of Old Manali lined with cozy wooden cafes playing live reggae and rock music.",
        "opening_hours": ["Monday-Sunday: 09:00-23:30"], "skip_if": "None; cafes are the perfect rainy-day refuge in Manali.",
        "insider_tip": "Visit Dylan's Toasted & Roasted for amazing cookies and Cafe 1947 for firewood pizzas next to the river.",
        "confidence_pct": 95
    },
    {
        "activity_id": "vashisht_springs_manali_06", "destination": "Manali", "name": "Vashisht Hot Springs & Temple",
        "category": "spiritual", "duration_minutes": 60, "cost_per_person": 0,
        "available_slots": ["07:00", "09:00", "15:00", "17:00"], "risk_level": "low",
        "tags": ["spiritual", "springs", "wellness", "temple"], "lat": 32.2612, "lng": 77.1905,
        "fatigue_score_base": 2, "morale_score_base": 7, "best_time_of_day": "morning",
        "best_season": ["Oct-Jun"], "accessibility": "easy",
        "editorial_summary": "Natural sulfurous hot water springs with healing properties, located next to a stone Sage Vashisht temple.",
        "opening_hours": ["Monday-Sunday: 07:00-13:00, 14:00-21:00"], "skip_if": "None; springs are great to soak in when it's freezing outside.",
        "insider_tip": "There are separate indoor bathing sections for men and women. Bring your own towel.",
        "confidence_pct": 98
    },
    {
        "activity_id": "manu_temple_manali_07", "destination": "Manali", "name": "Manu Temple Heritage Visit",
        "category": "spiritual", "duration_minutes": 60, "cost_per_person": 0,
        "available_slots": ["09:00", "11:00", "14:30", "16:00"], "risk_level": "low",
        "tags": ["spiritual", "temple", "heritage", "history"], "lat": 32.2562, "lng": 77.1722,
        "fatigue_score_base": 3, "morale_score_base": 7, "best_time_of_day": "morning",
        "best_season": ["Oct-Jun"], "accessibility": "moderate",
        "editorial_summary": "The only temple in India dedicated to Sage Manu, the creator of human race in Hindu mythology.",
        "opening_hours": ["Monday-Sunday: 06:00-17:00"], "skip_if": "None; located at the highest point of Old Manali village road.",
        "insider_tip": "Walk up through Old Manali village to see traditional Himachali wood-and-stone houses (Kathuni-Kuni style).",
        "confidence_pct": 97
    },
    {
        "activity_id": "tibetan_monastery_manali_08", "destination": "Manali", "name": "Gadhan Thekchhokling Tibetan Monastery",
        "category": "spiritual", "duration_minutes": 60, "cost_per_person": 20,
        "available_slots": ["09:00", "12:00", "15:00", "17:00"], "risk_level": "low",
        "tags": ["spiritual", "monastery", "buddhism", "crafts"], "lat": 32.2415, "lng": 77.1855,
        "fatigue_score_base": 2, "morale_score_base": 7, "best_time_of_day": "morning",
        "best_season": ["Oct-Jun"], "accessibility": "easy",
        "editorial_summary": "A colorful Buddhist monastery built by Tibetan refugees, housing a large gilded Buddha statue.",
        "opening_hours": ["Monday-Sunday: 06:00-18:00"], "skip_if": "None; situated close to Manali Mall Road.",
        "insider_tip": "Explore the small market run by monks next to the temple to buy handmade carpets and woven shawls.",
        "confidence_pct": 98
    },
    {
        "activity_id": "mall_road_manali_09", "destination": "Manali", "name": "Mall Road Shopping & Local Food",
        "category": "shopping", "duration_minutes": 120, "cost_per_person": 0,
        "available_slots": ["11:00", "14:30", "17:00", "19:00"], "risk_level": "low",
        "tags": ["shopping", "bazaar", "food", "family"], "lat": 32.2422, "lng": 77.1883,
        "fatigue_score_base": 2, "morale_score_base": 7, "best_time_of_day": "evening",
        "best_season": ["Oct-Jun"], "accessibility": "easy",
        "editorial_summary": "Manali's pedestrian-only main commercial street, full of shawl shops and local food stalls.",
        "opening_hours": ["Monday-Sunday: 10:00-22:00"], "skip_if": "None; very active street night scene.",
        "insider_tip": "Try the hot steamed momos and fresh fruit softies sold at the tiny side lane stalls.",
        "confidence_pct": 98
    },
    {
        "activity_id": "solang_ropeway_manali_10", "destination": "Manali", "name": "Solang Valley Ropeway Cable Car",
        "category": "nature", "duration_minutes": 90, "cost_per_person": 700,
        "available_slots": ["09:30", "11:30", "14:00", "15:30"], "risk_level": "low",
        "tags": ["nature", "cable_car", "viewpoint", "mountains", "scenic"], "lat": 32.3150, "lng": 77.1590,
        "fatigue_score_base": 2, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Oct-Jun"], "accessibility": "easy",
        "editorial_summary": "Take a modern cable car ride up to Anjani Mahadev peak for spectacular mountain panoramas.",
        "opening_hours": ["Monday-Sunday: 09:30-17:00"], "skip_if": "Electrical storms or heavy winds.",
        "insider_tip": "Combine with a trek to the Anjani Mahadev waterfall temple, which turns into an ice lingam in winter.",
        "confidence_pct": 96
    },
    {
        "activity_id": "naggar_castle_manali_11", "destination": "Manali", "name": "Naggar Castle Wooden Heritage Tour",
        "category": "cultural", "duration_minutes": 120, "cost_per_person": 100,
        "available_slots": ["09:30", "11:30", "14:00", "15:30"], "risk_level": "low",
        "tags": ["heritage", "castle", "architecture", "scenic"], "lat": 32.1128, "lng": 77.1890,
        "fatigue_score_base": 3, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Oct-Jun"], "accessibility": "easy",
        "editorial_summary": "A stunning 15th-century wood-and-stone castle built by Raja Sidh Singh, overlooking the Beas valley.",
        "opening_hours": ["Monday-Sunday: 09:00-18:00"], "skip_if": "None; easily accessible via road (20km from Manali).",
        "insider_tip": "The castle has a cozy open courtyard restaurant serving local trout fish and traditional tea.",
        "confidence_pct": 98
    },
    {
        "activity_id": "atal_tunnel_manali_12", "destination": "Manali", "name": "Atal Tunnel & Lahaul Valley Drive",
        "category": "adventure", "duration_minutes": 240, "cost_per_person": 0,
        "available_slots": ["08:30", "10:30", "13:00"], "risk_level": "medium",
        "tags": ["adventure", "tunnel", "roadtrip", "mountains", "scenic"], "lat": 32.3644, "lng": 77.1333,
        "fatigue_score_base": 4, "morale_score_base": 9, "best_time_of_day": "morning",
        "best_season": ["Jun-Oct"], "accessibility": "moderate",
        "editorial_summary": "Drive through the 9.02 km long tunnel (world's longest highway tunnel above 10,000 feet) to the dry Sissu valley.",
        "opening_hours": ["Monday-Sunday: 24 Hours"], "skip_if": "Heavy snow blocking the access roads near Solang.",
        "insider_tip": "Cross the tunnel to Sissu village; the difference in landscape from lush green to arid barren mountains is dramatic.",
        "confidence_pct": 98
    },
    {
        "activity_id": "sissu_waterfall_manali_13", "destination": "Manali", "name": "Sissu Waterfall Day Excursion",
        "category": "nature", "duration_minutes": 180, "cost_per_person": 0,
        "available_slots": ["09:00", "13:00"], "risk_level": "low",
        "tags": ["nature", "waterfall", "scenic", "mountains"], "lat": 32.4760, "lng": 77.1265,
        "fatigue_score_base": 4, "morale_score_base": 9, "best_time_of_day": "morning",
        "best_season": ["Jun-Oct"], "accessibility": "moderate",
        "editorial_summary": "A gorgeous mountain waterfall cascading down rocky cliffs, visible right after crossing the Atal Tunnel.",
        "opening_hours": ["Monday-Sunday: 24 Hours"], "skip_if": "Winter freezes, which turn the waterfall into solid ice.",
        "insider_tip": "You can cross the suspension footbridge over the Chandra river to reach the base of the waterfall pool.",
        "confidence_pct": 95
    },
    {
        "activity_id": "nehru_kund_manali_14", "destination": "Manali", "name": "Nehru Kund Fresh Spring View",
        "category": "nature", "duration_minutes": 45, "cost_per_person": 0,
        "available_slots": ["09:00", "11:00", "14:00", "16:00"], "risk_level": "low",
        "tags": ["nature", "springs", "scenic"], "lat": 32.2853, "lng": 77.1952,
        "fatigue_score_base": 1, "morale_score_base": 6, "best_time_of_day": "morning",
        "best_season": ["Oct-Jun"], "accessibility": "easy",
        "editorial_summary": "A natural cold water spring named after India's first Prime Minister, Jawahar Lal Nehru, who drank from it.",
        "opening_hours": ["Monday-Sunday: 24 Hours"], "skip_if": "None; located directly on the Manali-Rohtang highway.",
        "insider_tip": "Stop here for a quick photo and a taste of the sweet, mineral-rich mountain water.",
        "confidence_pct": 97
    },
    {
        "activity_id": "van_vihar_manali_15", "destination": "Manali", "name": "Van Vihar National Park Boating",
        "category": "nature", "duration_minutes": 60, "cost_per_person": 30,
        "available_slots": ["10:00", "13:00", "15:00", "16:30"], "risk_level": "low",
        "tags": ["nature", "park", "lake", "boating", "family"], "lat": 32.2383, "lng": 77.1878,
        "fatigue_score_base": 2, "morale_score_base": 6, "best_time_of_day": "afternoon",
        "best_season": ["Oct-Jun"], "accessibility": "easy",
        "editorial_summary": "A municipal park filled with giant deodar cedar trees, bordering the roaring Beas River.",
        "opening_hours": ["Monday-Sunday: 08:00-19:00"], "skip_if": "Rainy weather, which stops the small paddle boat operations.",
        "insider_tip": "Great, quiet place to sit on benches under high shade trees while kids paddle in the small concrete pond.",
        "confidence_pct": 98
    },
    {
        "activity_id": "jagatsukh_temple_manali_16", "destination": "Manali", "name": "Jagatsukh Shiva Temple Heritage",
        "category": "spiritual", "duration_minutes": 60, "cost_per_person": 0,
        "available_slots": ["09:00", "11:00", "14:00"], "risk_level": "low",
        "tags": ["spiritual", "temple", "heritage", "history"], "lat": 32.2033, "lng": 77.2025,
        "fatigue_score_base": 2, "morale_score_base": 7, "best_time_of_day": "morning",
        "best_season": ["Oct-Jun"], "accessibility": "easy",
        "editorial_summary": "An ancient 8th-century Shikhara-style stone temple dedicated to Lord Shiva, in the former capital village.",
        "opening_hours": ["Monday-Sunday: 07:00-19:00"], "skip_if": "None; located 6km south of Manali town.",
        "insider_tip": "The temple houses rare stone carvings of Shiva and Parvati. It is quiet and less touristy.",
        "confidence_pct": 96
    },
    {
        "activity_id": "solang_quad_manali_17", "destination": "Manali", "name": "Solang Valley Quad Biking Tour",
        "category": "adventure", "duration_minutes": 60, "cost_per_person": 1200,
        "available_slots": ["09:30", "11:30", "14:00", "15:30"], "risk_level": "medium",
        "tags": ["adventure", "quad", "biking", "offroad"], "lat": 32.3160, "lng": 77.1620,
        "fatigue_score_base": 4, "morale_score_base": 8, "best_time_of_day": "afternoon",
        "best_season": ["Oct-May"], "accessibility": "easy",
        "editorial_summary": "Ride all-terrain ATVs through muddy forest tracks and river margins in Solang Valley.",
        "opening_hours": ["Monday-Sunday: 09:00-17:30"], "skip_if": "Heavy snow, which freezes the engines and blocks the mud track.",
        "insider_tip": "Bargain hard with the local operators; they often lower prices if you are in a group.",
        "confidence_pct": 91
    },
    {
        "activity_id": "gulaba_snow_manali_18", "destination": "Manali", "name": "Gulaba Snow Point Trek",
        "category": "adventure", "duration_minutes": 180, "cost_per_person": 0,
        "available_slots": ["08:30", "10:30"], "risk_level": "medium",
        "tags": ["adventure", "snow", "trekking", "scenic"], "lat": 32.3333, "lng": 77.2280,
        "fatigue_score_base": 5, "morale_score_base": 9, "best_time_of_day": "morning",
        "best_season": ["Nov-Apr"], "accessibility": "moderate",
        "editorial_summary": "A scenic mountain meadow that serves as the snow activities zone when Rohtang Pass is closed by snow.",
        "opening_hours": ["Monday-Sunday: 08:30-17:00"], "skip_if": "Avalanche warnings during peak blizzards.",
        "insider_tip": "Rent snow boots and warm suits at the roadside shops in Bahang before heading up; they are cheaper.",
        "confidence_pct": 93
    },
    {
        "activity_id": "club_house_manali_19", "destination": "Manali", "name": "Manali Club House Indoor Activities",
        "category": "experience", "duration_minutes": 120, "cost_per_person": 50,
        "available_slots": ["10:00", "13:00", "15:00", "17:00"], "risk_level": "low",
        "tags": ["experience", "games", "river_crossing", "family"], "lat": 32.2472, "lng": 77.1736,
        "fatigue_score_base": 3, "morale_score_base": 6, "best_time_of_day": "afternoon",
        "best_season": ["Oct-Jun"], "accessibility": "easy",
        "editorial_summary": "An amusement and activity center by the river, offering table tennis, go-karting, and ziplining.",
        "opening_hours": ["Monday-Sunday: 10:00-19:00"], "skip_if": "If you prefer natural hikes over commercial amusement parks.",
        "insider_tip": "Try the high-altitude zipline (river crossing) over the rapid waters of the Manalsu River.",
        "confidence_pct": 96
    },
    {
        "activity_id": "jogini_temple_manali_20", "destination": "Manali", "name": "Vashisht Old Village walk",
        "category": "cultural", "duration_minutes": 90, "cost_per_person": 0,
        "available_slots": ["09:00", "15:00", "16:30"], "risk_level": "low",
        "tags": ["culture", "walking", "heritage", "local"], "lat": 32.2610, "lng": 77.1910,
        "fatigue_score_base": 3, "morale_score_base": 7, "best_time_of_day": "morning",
        "best_season": ["Oct-Jun"], "accessibility": "easy",
        "editorial_summary": "Walk through Vashisht village, seeing old wooden temples, mountain goats, and traditional farming life.",
        "opening_hours": ["Monday-Sunday: 24 Hours"], "skip_if": "None; a quiet, scenic walk to escape Mall Road traffic.",
        "insider_tip": "Buy hand-woven Kullu socks and woolen caps directly from local women sitting on their verandahs.",
        "confidence_pct": 95
    }
]

# --- BANGALORE (12 Activities) ---
bangalore_activities = [
    {
        "activity_id": "lalbagh_garden_blr_01", "destination": "Bangalore", "name": "Lalbagh Botanical Garden walk",
        "category": "nature", "duration_minutes": 120, "cost_per_person": 30,
        "available_slots": ["07:30", "09:00", "16:00", "17:30"], "risk_level": "low",
        "tags": ["nature", "garden", "glasshouse", "scenic", "family"], "lat": 12.9507, "lng": 77.5844,
        "fatigue_score_base": 3, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "A 240-acre botanical garden housing rare tropical plants and a historic iron glasshouse modeled on London's Crystal Palace.",
        "opening_hours": ["Monday-Sunday: 06:00-19:00"], "skip_if": "Heavy afternoon sun (walking the long paths gets exhausting).",
        "insider_tip": "Visit during the morning slot (6-9 AM) when entry is free for walkers, and the air is fresh.",
        "confidence_pct": 99
    },
    {
        "activity_id": "bangalore_palace_blr_02", "destination": "Bangalore", "name": "Bangalore Palace Royal Audio Tour",
        "category": "cultural", "duration_minutes": 120, "cost_per_person": 250,
        "available_slots": ["10:30", "12:30", "14:30", "16:00"], "risk_level": "low",
        "tags": ["heritage", "palace", "royalty", "architecture"], "lat": 12.9980, "lng": 77.5920,
        "fatigue_score_base": 3, "morale_score_base": 8, "best_time_of_day": "afternoon",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "A majestic palace owned by the Mysore royal family, built to resemble Windsor Castle with turreted walls.",
        "opening_hours": ["Monday-Sunday: 10:00-17:30"], "skip_if": "If you are on a tight budget (foreigner and photo charges are steep).",
        "insider_tip": "The entry ticket includes an excellent audio guide that details the royal paintings and historic wooden carvings.",
        "confidence_pct": 99
    },
    {
        "activity_id": "cubbon_park_blr_03", "destination": "Bangalore", "name": "Cubbon Park Green Canopy Walk",
        "category": "nature", "duration_minutes": 90, "cost_per_person": 0,
        "available_slots": ["07:30", "09:00", "16:30"], "risk_level": "low",
        "tags": ["nature", "park", "trees", "relaxed"], "lat": 12.9780, "lng": 77.5960,
        "fatigue_score_base": 2, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "A massive green lung in the city center, filled with old bamboo groves, mahogany trees, and bandstands.",
        "opening_hours": ["Monday-Sunday: 06:00-20:00 (Vehicles banned on Sundays)"], "skip_if": "Midday traffic on weekdays makes it noisy.",
        "insider_tip": "Go on Sunday mornings when vehicular traffic is banned inside the park; you can see locals playing with pets on grass.",
        "confidence_pct": 98
    },
    {
        "activity_id": "tipu_palace_blr_04", "destination": "Bangalore", "name": "Tipu Sultan's Summer Palace",
        "category": "cultural", "duration_minutes": 60, "cost_per_person": 25,
        "available_slots": ["09:30", "11:30", "14:30", "16:00"], "risk_level": "low",
        "tags": ["heritage", "palace", "teakwood", "history"], "lat": 12.9593, "lng": 77.5737,
        "fatigue_score_base": 2, "morale_score_base": 7, "best_time_of_day": "morning",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "An elegant double-story palace built entirely of French rosewood/teakwood with ornate arches.",
        "opening_hours": ["Monday-Sunday: 08:30-17:30"], "skip_if": "None; a quick and central historical visit.",
        "insider_tip": "Look at the ground floor rooms which serve as a museum detailing the life of Tipu Sultan and his war rockets.",
        "confidence_pct": 98
    },
    {
        "activity_id": "nandi_hills_blr_05", "destination": "Bangalore", "name": "Nandi Hills Sunrise Lookout",
        "category": "nature", "duration_minutes": 240, "cost_per_person": 50,
        "available_slots": ["04:30"], "risk_level": "medium",
        "tags": ["nature", "sunrise", "mountains", "scenic", "roadtrip"], "lat": 13.3702, "lng": 77.6835,
        "fatigue_score_base": 4, "morale_score_base": 9, "best_time_of_day": "morning",
        "best_season": ["Oct-Feb"], "accessibility": "moderate",
        "editorial_summary": "A popular weekend road trip hill fort, offering views of sunrise over a blanket of morning clouds.",
        "opening_hours": ["Monday-Sunday: 06:00-18:00 (Hills entry starts 05:30)"], "skip_if": "Heavy weekend traffic jams (Sundays are highly congested).",
        "insider_tip": "Leave Bangalore by 4:00 AM to beat the massive crowd of bikers queueing at the foothills checkpoint.",
        "confidence_pct": 97
    },
    {
        "activity_id": "bannerghatta_safari_blr_06", "destination": "Bangalore", "name": "Bannerghatta National Park Safari",
        "category": "wildlife", "duration_minutes": 240, "cost_per_person": 350,
        "available_slots": ["09:30", "11:30", "14:00"], "risk_level": "medium",
        "tags": ["wildlife", "safari", "nature", "animals", "family"], "lat": 12.8009, "lng": 77.5772,
        "fatigue_score_base": 4, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "A biological reserve offering enclosed bus safaris to spot Bengal tigers, Asiatic lions, and bears.",
        "opening_hours": ["Wednesday-Monday: 09:30-17:00"], "skip_if": "Tuesdays, when the park is closed.",
        "insider_tip": "Book the AC jeep safari instead of the big bus; it gives you a much closer and quiet view of tigers.",
        "confidence_pct": 95
    },
    {
        "activity_id": "brewery_tour_blr_07", "destination": "Bangalore", "name": "Toit Brewpub Craft Beer Tasting",
        "category": "food", "duration_minutes": 120, "cost_per_person": 1000,
        "available_slots": ["13:00", "17:00", "19:30", "21:30"], "risk_level": "low",
        "tags": ["food", "brewery", "beer", "nightlife", "music"], "lat": 12.9790, "lng": 77.6405,
        "fatigue_score_base": 2, "morale_score_base": 9, "best_time_of_day": "night",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "Sample Bangalore's famous craft microbreweries, tasting flights of Hefeweizen and dark stouts.",
        "opening_hours": ["Monday-Sunday: 12:00-01:00"], "skip_if": "If you don't drink alcohol (though their wood-fired pizzas are great).",
        "insider_tip": "Book a table via telephone beforehand; wait times on Friday and Saturday nights can exceed 1.5 hours.",
        "confidence_pct": 94
    },
    {
        "activity_id": "vv_puram_food_blr_08", "destination": "Bangalore", "name": "VV Puram Thindi Beedi Street Food",
        "category": "food", "duration_minutes": 90, "cost_per_person": 200,
        "available_slots": ["18:00", "19:30", "21:00"], "risk_level": "low",
        "tags": ["food", "street_food", "vegetarian", "local"], "lat": 12.9512, "lng": 77.5780,
        "fatigue_score_base": 3, "morale_score_base": 8, "best_time_of_day": "evening",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "A famous street food lane serving delicious South Indian vegetarian delicacies like akki roti and paddu.",
        "opening_hours": ["Monday-Sunday: 18:00-23:00"], "skip_if": "If you expect upscale seating; it is strictly a walk-and-eat lane.",
        "insider_tip": "Try the 'Avarebele' (hyacinth bean) specials and the hot butter dosas at the Arya Vysya Refreshments stall.",
        "confidence_pct": 96
    },
    {
        "activity_id": "commercial_street_blr_09", "destination": "Bangalore", "name": "Commercial Street Bargain Shopping",
        "category": "shopping", "duration_minutes": 120, "cost_per_person": 0,
        "available_slots": ["11:00", "14:00", "17:00"], "risk_level": "low",
        "tags": ["shopping", "bazaar", "textiles", "clothes"], "lat": 12.9822, "lng": 77.6083,
        "fatigue_score_base": 3, "morale_score_base": 7, "best_time_of_day": "evening",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "A chaotic and bustling marketplace famous for clothing, footwear, trinkets, and cosmetics.",
        "opening_hours": ["Monday-Sunday: 11:00-21:00"], "skip_if": "If you dislike heavily packed streets and narrow walk paths.",
        "insider_tip": "Explore the smaller cross-lanes for the best deals on silver trinkets and ethnic footwear.",
        "confidence_pct": 98
    },
    {
        "activity_id": "iskcon_temple_blr_10", "destination": "Bangalore", "name": "ISKCON Radha Krishna Temple",
        "category": "spiritual", "duration_minutes": 90, "cost_per_person": 0,
        "available_slots": ["09:00", "11:00", "16:30", "18:30"], "risk_level": "low",
        "tags": ["spiritual", "temple", "culture", "krishna"], "lat": 13.0094, "lng": 77.5510,
        "fatigue_score_base": 3, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "One of the largest ISKCON temples in the world, featuring modern glass architecture on a hillock.",
        "opening_hours": ["Monday-Sunday: 04:15-05:00, 07:15-13:00, 16:15-20:30"], "skip_if": "Camera usage: taking photos inside the shrine is strictly banned.",
        "insider_tip": "Do not skip buying the hot sweet prasadam (ladoos and khichdi) sold at the exit counters.",
        "confidence_pct": 98
    },
    {
        "activity_id": "vidhana_soudha_blr_11", "destination": "Bangalore", "name": "Vidhana Soudha Architecture Photo Stop",
        "category": "cultural", "duration_minutes": 45, "cost_per_person": 0,
        "available_slots": ["09:00", "12:00", "16:00", "18:30"], "risk_level": "low",
        "tags": ["architecture", "government", "heritage", "photography"], "lat": 12.9796, "lng": 77.5908,
        "fatigue_score_base": 1, "morale_score_base": 7, "best_time_of_day": "evening",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "A massive, imposing neo-Dravidian granite building housing the state legislature of Karnataka.",
        "opening_hours": ["Monday-Friday: 09:00-17:00 (Entry inside requires special government permission)"], "skip_if": "Interior entry is not open to tourists; it's strictly a roadside photo stop.",
        "insider_tip": "View it on Sunday evenings (6:30-8:30 PM) when the entire granite facade is illuminated with thousands of lights.",
        "confidence_pct": 98
    },
    {
        "activity_id": "visvesvaraya_museum_blr_12", "destination": "Bangalore", "name": "Visvesvaraya Science Museum Tour",
        "category": "cultural", "duration_minutes": 150, "cost_per_person": 85,
        "available_slots": ["10:30", "13:00", "15:00"], "risk_level": "low",
        "tags": ["museum", "science", "interactive", "family"], "lat": 12.9753, "lng": 77.5964,
        "fatigue_score_base": 3, "morale_score_base": 7, "best_time_of_day": "afternoon",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "A fun, interactive science museum containing engines, space models, and a Wright brothers aircraft replica.",
        "opening_hours": ["Monday-Sunday: 10:00-18:00"], "skip_if": "None; perfect place for families and science buffs.",
        "insider_tip": "Check out the dinosaur enclave on the ground floor which features a moving animatronic T-Rex model.",
        "confidence_pct": 98
    }
]

# --- KOLKATA (12 Activities) ---
kolkata_activities = [
    {
        "activity_id": "victoria_memorial_kol_01", "destination": "Kolkata", "name": "Victoria Memorial Palace & Gardens",
        "category": "cultural", "duration_minutes": 120, "cost_per_person": 60,
        "available_slots": ["10:00", "12:00", "14:00", "16:00"], "risk_level": "low",
        "tags": ["heritage", "palace", "marble", "museum", "gardens"], "lat": 22.5448, "lng": 88.3425,
        "fatigue_score_base": 3, "morale_score_base": 9, "best_time_of_day": "evening",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "A magnificent white Makrana marble monument dedicated to Queen Victoria, surrounded by wide garden pools.",
        "opening_hours": ["Monday-Sunday: 10:00-18:00 (Gardens open 05:30-18:15)"], "skip_if": "Heavily foggy winter mornings (obscures the white dome).",
        "insider_tip": "Stay for the evening light and sound show which narrates Kolkata's colonial history.",
        "confidence_pct": 99
    },
    {
        "activity_id": "howrah_bridge_kol_02", "destination": "Kolkata", "name": "Howrah Bridge & Mullick Ghat Flower Market",
        "category": "cultural", "duration_minutes": 90, "cost_per_person": 0,
        "available_slots": ["06:30", "08:00", "16:30"], "risk_level": "low",
        "tags": ["bridge", "market", "heritage", "photography", "local"], "lat": 22.5850, "lng": 88.3584,
        "fatigue_score_base": 4, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Oct-Mar"], "accessibility": "moderate",
        "editorial_summary": "Walk through one of the world's busiest cantilever bridges next to a chaotic, colorful riverside flower market.",
        "opening_hours": ["Monday-Sunday: 24 Hours (Market is best at dawn)"], "skip_if": "If you are highly sensitive to intense mud, crowds, and damp smells.",
        "insider_tip": "Arrive at the flower market by 6:00 AM to see wrestlers exercising next to heaps of orange marigolds.",
        "confidence_pct": 98
    },
    {
        "activity_id": "dakshineswar_temple_kol_03", "destination": "Kolkata", "name": "Dakshineswar Kali Temple River Visit",
        "category": "spiritual", "duration_minutes": 120, "cost_per_person": 0,
        "available_slots": ["07:30", "09:30", "15:30", "17:00"], "risk_level": "low",
        "tags": ["spiritual", "temple", "kali", "river", "history"], "lat": 22.6550, "lng": 88.3580,
        "fatigue_score_base": 3, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "A 19th-century temple shrine dedicated to Goddess Bhavatarini, where saint Ramakrishna lived and preached.",
        "opening_hours": ["Monday-Sunday: 06:00-12:30, 15:30-21:00"], "skip_if": "Security rules: phones and cameras are banned inside the temple enclosure.",
        "insider_tip": "Take a local ferry from Dakshineswar Ghat across the river to Belur Math; it's cheap and highly scenic.",
        "confidence_pct": 98
    },
    {
        "activity_id": "belur_math_kol_04", "destination": "Kolkata", "name": "Belur Math Ramakrishna Mission",
        "category": "spiritual", "duration_minutes": 90, "cost_per_person": 0,
        "available_slots": ["08:30", "10:30", "16:00", "17:30"], "risk_level": "low",
        "tags": ["spiritual", "temple", "peaceful", "architecture"], "lat": 22.6300, "lng": 88.3533,
        "fatigue_score_base": 2, "morale_score_base": 9, "best_time_of_day": "morning",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "The headquarters of Ramakrishna Mission, combining Hindu, Christian, and Islamic motifs in its temple architecture.",
        "opening_hours": ["Monday-Sunday: 06:00-11:00, 16:00-19:00"], "skip_if": "No photography allowed inside the main prayer hall.",
        "insider_tip": "Sit quietly in the main prayer hall for 15 minutes during evening arati; the peace is incredible.",
        "confidence_pct": 98
    },
    {
        "activity_id": "indian_museum_kol_05", "destination": "Kolkata", "name": "Indian Museum Colonial Gallery Tour",
        "category": "cultural", "duration_minutes": 150, "cost_per_person": 150,
        "available_slots": ["10:30", "13:00", "15:00"], "risk_level": "low",
        "tags": ["museum", "history", "antiquities", "family"], "lat": 22.5578, "lng": 88.3512,
        "fatigue_score_base": 3, "morale_score_base": 8, "best_time_of_day": "afternoon",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "Founded in 1814, it is India's oldest and largest museum, housing an Egyptian mummy and dinosaur fossils.",
        "opening_hours": ["Tuesday-Sunday: 10:00-18:00"], "skip_if": "Mondays, when the museum is closed.",
        "insider_tip": "Check out the Bharhut Buddhist stupa gallery; the stone carvings are over 2,000 years old.",
        "confidence_pct": 98
    },
    {
        "activity_id": "park_street_dining_kol_06", "destination": "Kolkata", "name": "Park Street Heritage Restaurant Dinner",
        "category": "food", "duration_minutes": 120, "cost_per_person": 800,
        "available_slots": ["13:00", "18:00", "20:00", "22:00"], "risk_level": "low",
        "tags": ["food", "heritage", "restaurants", "nightlife"], "lat": 22.5488, "lng": 88.3533,
        "fatigue_score_base": 1, "morale_score_base": 9, "best_time_of_day": "night",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "Kolkata's premier lifestyle dining street, famous for iconic colonial-era restaurants and pubs.",
        "opening_hours": ["Monday-Sunday: 11:00-23:30"], "skip_if": "None; a must-visit dining hub in Kolkata.",
        "insider_tip": "Get a cabin table at Mocambo and order their legendary devilled crabs and chicken Stroganoff.",
        "confidence_pct": 97
    },
    {
        "activity_id": "marble_palace_kol_07", "destination": "Kolkata", "name": "Marble Palace Private Mansion Tour",
        "category": "cultural", "duration_minutes": 90, "cost_per_person": 0,
        "available_slots": ["10:30", "12:30", "14:30"], "risk_level": "low",
        "tags": ["heritage", "palace", "mansion", "history", "offbeat"], "lat": 22.5806, "lng": 88.3590,
        "fatigue_score_base": 2, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "A grand 19th-century private mansion built of Italian marble, full of antique statues and paintings.",
        "opening_hours": ["Tuesday, Wednesday, Friday-Sunday: 10:00-16:00"], "skip_if": "Mondays and Thursdays. Note: requires a free pass from West Bengal Tourism Office.",
        "insider_tip": "You must obtain a free permit from the West Bengal Tourism office in BBD Bagh a day before visiting.",
        "confidence_pct": 92
    },
    {
        "activity_id": "kumartuli_potters_kol_08", "destination": "Kolkata", "name": "Kumartuli Clay Idol Potters Colony Walk",
        "category": "experience", "duration_minutes": 90, "cost_per_person": 0,
        "available_slots": ["10:00", "14:30", "16:00"], "risk_level": "low",
        "tags": ["experience", "crafts", "pottery", "culture", "photography"], "lat": 22.6022, "lng": 88.3610,
        "fatigue_score_base": 3, "morale_score_base": 9, "best_time_of_day": "afternoon",
        "best_season": ["Aug-Oct"], "accessibility": "moderate",
        "editorial_summary": "Walk through narrow lanes where local artisans sculpt straw and clay into massive Hindu god idols.",
        "opening_hours": ["Monday-Sunday: 09:00-20:00"], "skip_if": "If you dislike muddy lanes (especially during monsoon prep).",
        "insider_tip": "Visit in August and September (before Durga Puja) to see the artisans painting the eyes of Durga idols.",
        "confidence_pct": 94
    },
    {
        "activity_id": "college_street_kol_09", "destination": "Kolkata", "name": "College Street Book Market & Coffee House",
        "category": "shopping", "duration_minutes": 120, "cost_per_person": 0,
        "available_slots": ["11:00", "14:30", "16:30"], "risk_level": "low",
        "tags": ["shopping", "books", "cafe", "history", "culture"], "lat": 22.5745, "lng": 88.3633,
        "fatigue_score_base": 3, "morale_score_base": 8, "best_time_of_day": "afternoon",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "The world's largest second-hand book market, stretching over a mile with small wooden stalls.",
        "opening_hours": ["Monday-Saturday: 10:00-20:00 (Sundays closed)"], "skip_if": "Sundays, when all bookstalls are closed.",
        "insider_tip": "Head to the Indian Coffee House upstairs, grab a table, and order cold coffee while listening to local student debates.",
        "confidence_pct": 98
    },
    {
        "activity_id": "birla_planetarium_kol_10", "destination": "Kolkata", "name": "Birla Planetarium Space Show",
        "category": "cultural", "duration_minutes": 60, "cost_per_person": 100,
        "available_slots": ["12:30", "14:30", "16:30"], "risk_level": "low",
        "tags": ["museum", "science", "space", "family"], "lat": 22.5458, "lng": 88.3478,
        "fatigue_score_base": 1, "morale_score_base": 7, "best_time_of_day": "afternoon",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "The largest planetarium in Asia, featuring dome projections of the night sky and space history.",
        "opening_hours": ["Monday-Sunday: 11:30-19:00"], "skip_if": "None; great place to cool off in the AC.",
        "insider_tip": "Check the show schedule online; they run shows in English, Hindi, and Bengali at different times.",
        "confidence_pct": 98
    },
    {
        "activity_id": "mother_house_kol_11", "destination": "Kolkata", "name": "Mother House Saint Teresa Tomb",
        "category": "spiritual", "duration_minutes": 60, "cost_per_person": 0,
        "available_slots": ["09:00", "11:00", "15:00", "16:30"], "risk_level": "low",
        "tags": ["spiritual", "history", "peaceful"], "lat": 22.5489, "lng": 77.3600, # Wait, lng for Kolkata is 88, let's fix it:
        "lat": 22.5489, "lng": 88.3622,
        "fatigue_score_base": 1, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "The home and final resting place of Mother Teresa, showcasing her small room and personal items.",
        "opening_hours": ["Friday-Wednesday: 08:00-12:00, 15:00-17:30"], "skip_if": "Thursdays, when the house is closed to public.",
        "insider_tip": "Maintain silence inside. The small room where Mother Teresa lived is kept exactly as she left it.",
        "confidence_pct": 97
    },
    {
        "activity_id": "eden_gardens_kol_12", "destination": "Kolkata", "name": "Eden Gardens Stadium Photo Stop",
        "category": "cultural", "duration_minutes": 45, "cost_per_person": 0,
        "available_slots": ["09:00", "12:00", "15:00"], "risk_level": "low",
        "tags": ["stadium", "sports", "cricket", "photography"], "lat": 22.5642, "lng": 88.3433,
        "fatigue_score_base": 2, "morale_score_base": 6, "best_time_of_day": "morning",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "India's oldest and most iconic cricket stadium, famous for its roaring, passionate crowds.",
        "opening_hours": ["Monday-Sunday: 09:00-17:00 (Entry inside fields restricted when no matches are scheduled)"], "skip_if": "If you cannot get a ticket on match days; general tour entry is restricted.",
        "insider_tip": "You can capture a great photo of the stadium's historic gates from the Maidan fields across the street.",
        "confidence_pct": 98
    }
]

# --- SHILLONG (12 Activities) ---
shillong_activities = [
    {
        "activity_id": "umiam_lake_shillong_01", "destination": "Shillong", "name": "Umiam Lake Boating & Viewpoint",
        "category": "water_sport", "duration_minutes": 120, "cost_per_person": 300,
        "available_slots": ["09:30", "11:30", "14:00", "15:30"], "risk_level": "low",
        "tags": ["lake", "boating", "scenic", "nature", "family"], "lat": 25.6420, "lng": 91.8920,
        "fatigue_score_base": 2, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Sep-May"], "accessibility": "easy",
        "editorial_summary": "A massive, beautiful blue water reservoir surrounded by lush pine hills, resembling Swiss lakes.",
        "opening_hours": ["Monday-Sunday: 09:00-17:00"], "skip_if": "Heavy rains or low water levels.",
        "insider_tip": "Stop at the viewpoint on the main Guwahati highway first to capture the scale of the lake under pine trees.",
        "confidence_pct": 98
    },
    {
        "activity_id": "elephant_falls_shillong_02", "destination": "Shillong", "name": "Elephant Falls Three-Tiered Walk",
        "category": "nature", "duration_minutes": 90, "cost_per_person": 50,
        "available_slots": ["09:00", "11:00", "13:30", "15:00"], "risk_level": "low",
        "tags": ["nature", "waterfall", "scenic", "family"], "lat": 25.5367, "lng": 91.8217,
        "fatigue_score_base": 3, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Jun-Dec"], "accessibility": "moderate",
        "editorial_summary": "A three-step waterfall cascading down fern-covered rocks, with paved paths leading to each pool.",
        "opening_hours": ["Monday-Sunday: 09:00-17:00"], "skip_if": "Peak dry summer (April) when the flow gets very thin.",
        "insider_tip": "Rent traditional Khasi attire at the entry shop for a fun photo shoot next to the falls.",
        "confidence_pct": 98
    },
    {
        "activity_id": "laitlum_canyons_shillong_03", "destination": "Shillong", "name": "Laitlum Canyons Gorge Lookout",
        "category": "nature", "duration_minutes": 180, "cost_per_person": 50,
        "available_slots": ["06:00", "09:00", "14:30"], "risk_level": "medium",
        "tags": ["nature", "canyons", "gorge", "clouds", "scenic", "offbeat"], "lat": 25.4388, "lng": 91.9755,
        "fatigue_score_base": 5, "morale_score_base": 10, "best_time_of_day": "morning",
        "best_season": ["Sep-May"], "accessibility": "moderate",
        "editorial_summary": "Dramatic, green cliff edges dropping into deep valleys, often covered in flowing cloud mist.",
        "opening_hours": ["Monday-Sunday: 06:00-17:30"], "skip_if": "Dense monsoon storm days (clouds block the entire gorge view).",
        "insider_tip": "Walk down the steep stone stairs built into the ridge to see the tiny village of Rasong at the bottom.",
        "confidence_pct": 95
    },
    {
        "activity_id": "shillong_peak_shillong_04", "destination": "Shillong", "name": "Shillong Peak Skyline Lookout",
        "category": "nature", "duration_minutes": 90, "cost_per_person": 50,
        "available_slots": ["09:00", "11:00", "14:00", "15:30"], "risk_level": "low",
        "tags": ["nature", "viewpoint", "mountains", "scenic"], "lat": 25.5342, "lng": 91.8595,
        "fatigue_score_base": 2, "morale_score_base": 7, "best_time_of_day": "morning",
        "best_season": ["Sep-May"], "accessibility": "easy",
        "editorial_summary": "The highest peak in Meghalaya (1,965m), offering views of the city below and far-off Bangladesh plains.",
        "opening_hours": ["Monday-Sunday: 09:00-15:30"], "skip_if": "Ensure you carry a passport/ID card; it's located inside an active Air Force base checkpoint.",
        "insider_tip": "Foreign nationals are sometimes restricted entry here due to defense rules; check current status.",
        "confidence_pct": 96
    },
    {
        "activity_id": "don_bosco_shillong_05", "destination": "Shillong", "name": "Don Bosco Museum of Indigenous Cultures",
        "category": "cultural", "duration_minutes": 150, "cost_per_person": 150,
        "available_slots": ["09:30", "11:30", "14:00", "15:00"], "risk_level": "low",
        "tags": ["museum", "culture", "heritage", "history"], "lat": 25.5902, "lng": 91.8885,
        "fatigue_score_base": 3, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Sep-May"], "accessibility": "easy",
        "editorial_summary": "A 7-story hexagonal building showcasing the rich lifestyle, fabrics, and weapons of Northeast tribes.",
        "opening_hours": ["Monday-Saturday: 09:00-17:30"], "skip_if": "Sundays and national holidays, when the museum is closed.",
        "insider_tip": "Go all the way to the top floor to walk the glass skywalk offering views of Shillong city.",
        "confidence_pct": 98
    },
    {
        "activity_id": "police_bazar_shillong_06", "destination": "Shillong", "name": "Police Bazar shopping & street eats",
        "category": "shopping", "duration_minutes": 120, "cost_per_person": 0,
        "available_slots": ["11:00", "14:00", "16:30", "18:30"], "risk_level": "low",
        "tags": ["shopping", "bazaar", "food", "family"], "lat": 25.5783, "lng": 91.8828,
        "fatigue_score_base": 2, "morale_score_base": 7, "best_time_of_day": "evening",
        "best_season": ["Sep-May"], "accessibility": "easy",
        "editorial_summary": "Shillong's main pedestrian market circle, famous for winter clothes, bamboo crafts, and local pork momos.",
        "opening_hours": ["Monday-Saturday: 10:00-20:30 (Sundays closed)"], "skip_if": "Sundays, when the bazaar is completely quiet.",
        "insider_tip": "Try the piping hot pork and vegetable momos sold at the small carts near the central roundabout.",
        "confidence_pct": 98
    },
    {
        "activity_id": "sacred_forest_shillong_07", "destination": "Shillong", "name": "Mawphlang Sacred Grove Walk",
        "category": "nature", "duration_minutes": 150, "cost_per_person": 100,
        "available_slots": ["09:00", "11:30", "14:00"], "risk_level": "low",
        "tags": ["nature", "forest", "sacred", "culture", "walking"], "lat": 25.4499, "lng": 91.7583,
        "fatigue_score_base": 4, "morale_score_base": 9, "best_time_of_day": "morning",
        "best_season": ["Sep-May"], "accessibility": "moderate",
        "editorial_summary": "An ancient sacred forest protected by Khasi deities; custom forbids taking anything out of the forest.",
        "opening_hours": ["Monday-Sunday: 09:00-17:00"], "skip_if": "Failing to respect local custom (do not pick even a dry leaf or twig).",
        "insider_tip": "Hire a local Khasi guide at the forest entrance. They will explain the sacrificial stone tables and medicinal plants.",
        "confidence_pct": 95
    },
    {
        "activity_id": "wards_lake_shillong_08", "destination": "Shillong", "name": "Ward's Lake Botanical Park",
        "category": "nature", "duration_minutes": 60, "cost_per_person": 30,
        "available_slots": ["09:00", "11:00", "14:00", "16:00"], "risk_level": "low",
        "tags": ["nature", "lake", "park", "family", "scenic"], "lat": 25.5786, "lng": 91.8860,
        "fatigue_score_base": 2, "morale_score_base": 7, "best_time_of_day": "morning",
        "best_season": ["Sep-May"], "accessibility": "easy",
        "editorial_summary": "An artificial horseshoe lake surrounded by terraced gardens and a wooden bridge, dating back to 1894.",
        "opening_hours": ["Monday-Sunday: 08:30-17:30"], "skip_if": "Rainy weather.",
        "insider_tip": "Buy fish food pellets at the entry gate to feed the thousands of golden carps from the bridge.",
        "confidence_pct": 98
    },
    {
        "activity_id": "david_scott_shillong_09", "destination": "Shillong", "name": "David Scott Trail Trekking",
        "category": "adventure", "duration_minutes": 360, "cost_per_person": 800,
        "available_slots": ["07:30"], "risk_level": "medium",
        "tags": ["adventure", "trekking", "history", "forest", "scenic"], "lat": 25.4650, "lng": 91.7310,
        "fatigue_score_base": 7, "morale_score_base": 9, "best_time_of_day": "morning",
        "best_season": ["Oct-Apr"], "accessibility": "difficult",
        "editorial_summary": "A historic 16km British-era horse track trek through streams, green meadows, and pine gorges.",
        "opening_hours": ["Monday-Sunday: 06:00-17:00"], "skip_if": "Peak monsoons, as stream crossings can be dangerous.",
        "insider_tip": "Hire a local guide from Mawphlang village. Pack plenty of water and protein snacks for the 5-hour walk.",
        "confidence_pct": 91
    },
    {
        "activity_id": "sweet_falls_shillong_10", "destination": "Shillong", "name": "Sweet Falls Steep Lookout",
        "category": "nature", "duration_minutes": 60, "cost_per_person": 50,
        "available_slots": ["09:30", "12:00", "15:00"], "risk_level": "medium",
        "tags": ["nature", "waterfall", "scenic"], "lat": 25.5612, "lng": 91.9320,
        "fatigue_score_base": 2, "morale_score_base": 6, "best_time_of_day": "morning",
        "best_season": ["Jun-Dec"], "accessibility": "easy",
        "editorial_summary": "One of Shillong's steepest single-fall waterfalls, falling 96 meters into a deep canyon gorge.",
        "opening_hours": ["Monday-Sunday: 09:00-17:00"], "skip_if": "Monsoon fog, which obscures the vertical water cascade.",
        "insider_tip": "Do not attempt to walk down the steep gorge cliffs; it's extremely dangerous and banned.",
        "confidence_pct": 96
    },
    {
        "activity_id": "cathedral_shillong_11", "destination": "Shillong", "name": "Cathedral of Mary Help of Christians",
        "category": "spiritual", "duration_minutes": 45, "cost_per_person": 0,
        "available_slots": ["09:00", "11:00", "14:00", "16:00"], "risk_level": "low",
        "tags": ["spiritual", "cathedral", "church", "peaceful"], "lat": 25.5683, "lng": 91.8992,
        "fatigue_score_base": 1, "morale_score_base": 7, "best_time_of_day": "morning",
        "best_season": ["Sep-May"], "accessibility": "easy",
        "editorial_summary": "A grand, gothic-style Catholic church in blue, standing on sand foundation to resist earthquakes.",
        "opening_hours": ["Monday-Sunday: 07:00-18:00"], "skip_if": "Dress modestly and maintain silence.",
        "insider_tip": "Look at the high stained glass windows depicting bible scenes imported from Munich, Germany.",
        "confidence_pct": 97
    },
    {
        "activity_id": "hydari_park_shillong_12", "destination": "Shillong", "name": "Lady Hydari Park & Mini Zoo",
        "category": "nature", "duration_minutes": 60, "cost_per_person": 20,
        "available_slots": ["09:30", "12:00", "14:30", "16:00"], "risk_level": "low",
        "tags": ["nature", "park", "zoo", "family"], "lat": 25.5680, "lng": 91.8845,
        "fatigue_score_base": 2, "morale_score_base": 5, "best_time_of_day": "afternoon",
        "best_season": ["Sep-May"], "accessibility": "easy",
        "editorial_summary": "A Japanese-style landscaped garden housing a mini-zoo with local deer, black bears, and birds.",
        "opening_hours": ["Tuesday-Sunday: 09:00-17:00"], "skip_if": "Mondays, when the park is closed.",
        "insider_tip": "Great, quiet spot to relax with kids in the heart of Shillong. The pine paths are pleasant.",
        "confidence_pct": 98
    }
]
