# --- MUNNAR (20 Activities) ---
munnar_activities = [
    {
        "activity_id": "eravikulam_park_munnar_01", "destination": "Munnar", "name": "Eravikulam National Park Safari",
        "category": "wildlife", "duration_minutes": 180, "cost_per_person": 200,
        "available_slots": ["07:30", "09:00", "11:00", "14:00"], "risk_level": "low",
        "tags": ["wildlife", "safari", "nature", "trekking", "hills"], "lat": 10.1500, "lng": 77.0600,
        "fatigue_score_base": 4, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Sep-May"], "accessibility": "moderate",
        "editorial_summary": "The sanctuary of the endangered Nilgiri Tahr, offering panoramic views of misty green slopes and tea gardens.",
        "opening_hours": ["Monday-Sunday: 07:30-16:00"], "skip_if": "Calving season (Feb-March) when the park is closed.",
        "insider_tip": "Book your tickets online beforehand to skip the massive physical queue at the entry gate.",
        "confidence_pct": 96
    },
    {
        "activity_id": "tea_museum_munnar_02", "destination": "Munnar", "name": "Tata Tea Museum & Factory Tour",
        "category": "cultural", "duration_minutes": 90, "cost_per_person": 125,
        "available_slots": ["09:00", "11:00", "14:00", "15:30"], "risk_level": "low",
        "tags": ["museum", "tea", "history", "experience"], "lat": 10.0934, "lng": 77.0612,
        "fatigue_score_base": 2, "morale_score_base": 7, "best_time_of_day": "morning",
        "best_season": ["Oct-May"], "accessibility": "easy",
        "editorial_summary": "A museum detailing Munnar's history from 1880 tea plantation growth, with tea tasting sessions.",
        "opening_hours": ["Tuesday-Sunday: 09:00-17:00"], "skip_if": "Mondays, when the museum is closed.",
        "insider_tip": "Buy fresh cardamom tea and orthodox black tea packages directly from the factory store here.",
        "confidence_pct": 98
    },
    {
        "activity_id": "kolukkumalai_jeep_munnar_03", "destination": "Munnar", "name": "Kolukkumalai Sunrise Jeep Safari",
        "category": "adventure", "duration_minutes": 240, "cost_per_person": 1000,
        "available_slots": ["04:30"], "risk_level": "medium",
        "tags": ["adventure", "jeep", "sunrise", "scenic", "tea_gardens"], "lat": 10.0245, "lng": 77.2255,
        "fatigue_score_base": 6, "morale_score_base": 10, "best_time_of_day": "morning",
        "best_season": ["Sep-May"], "accessibility": "difficult",
        "editorial_summary": "Take a bumpy, off-road jeep ride to the world's highest organic tea estate for a spectacular sunrise above clouds.",
        "opening_hours": ["Monday-Sunday: 04:30-18:00"], "skip_if": "Heavy rains, which make the steep mud track too dangerous.",
        "insider_tip": "Wear a windcheater and carry a muffler; it gets freezing at the peak before the sun comes up.",
        "confidence_pct": 92
    },
    {
        "activity_id": "top_station_munnar_04", "destination": "Munnar", "name": "Top Station Viewpoint Hike",
        "category": "nature", "duration_minutes": 120, "cost_per_person": 50,
        "available_slots": ["08:00", "10:00", "15:00"], "risk_level": "low",
        "tags": ["nature", "viewpoint", "mountains", "scenic"], "lat": 10.1245, "lng": 77.2458,
        "fatigue_score_base": 5, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Oct-Apr"], "accessibility": "moderate",
        "editorial_summary": "The highest point in Munnar on the Kerala-Tamil Nadu border, famous for Neelakurinji flower blooms.",
        "opening_hours": ["Monday-Sunday: 06:00-18:00"], "skip_if": "Heavily foggy days, as visibility drops to zero.",
        "insider_tip": "Walk down the steps to the cliff edge for the best views, but remember the climb back up is steep.",
        "confidence_pct": 97
    },
    {
        "activity_id": "mattupetty_dam_munnar_05", "destination": "Munnar", "name": "Mattupetty Dam Boating & View",
        "category": "nature", "duration_minutes": 90, "cost_per_person": 300,
        "available_slots": ["09:30", "11:00", "14:00", "15:30"], "risk_level": "low",
        "tags": ["lake", "dam", "boating", "scenic", "family"], "lat": 10.1062, "lng": 77.1248,
        "fatigue_score_base": 2, "morale_score_base": 7, "best_time_of_day": "afternoon",
        "best_season": ["Oct-May"], "accessibility": "easy",
        "editorial_summary": "A storage concrete gravity dam in the hills, offering speedboats and reflection views of surrounding forests.",
        "opening_hours": ["Monday-Sunday: 09:30-17:00"], "skip_if": "High wind days or heavy monsoons.",
        "insider_tip": "Rent the speed boat instead of the slow group boat; it's thrilling and goes deeper into the reserve forest margins.",
        "confidence_pct": 98
    },
    {
        "activity_id": "lakkam_falls_munnar_06", "destination": "Munnar", "name": "Lakkam Waterfalls Pool Swim",
        "category": "nature", "duration_minutes": 60, "cost_per_person": 50,
        "available_slots": ["09:00", "11:00", "14:00", "16:00"], "risk_level": "low",
        "tags": ["nature", "waterfall", "swimming", "scenic"], "lat": 10.1833, "lng": 77.1167,
        "fatigue_score_base": 3, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Sep-Jan"], "accessibility": "easy",
        "editorial_summary": "A narrow waterfall cascading down rock boulders into a calm sandy pool suitable for foot-dipping.",
        "opening_hours": ["Monday-Sunday: 08:00-17:00"], "skip_if": "Heavy monsoons when flow is too violent.",
        "insider_tip": "There is a small eco-shop run by the forest department selling local forest honey and spices near the gate.",
        "confidence_pct": 95
    },
    {
        "activity_id": "punarjani_village_munnar_07", "destination": "Munnar", "name": "Punarjani Traditional Art Show",
        "category": "experience", "duration_minutes": 120, "cost_per_person": 400,
        "available_slots": ["17:00"], "risk_level": "low",
        "tags": ["experience", "culture", "kathakali", "martial_arts", "family"], "lat": 10.0542, "lng": 76.9932,
        "fatigue_score_base": 2, "morale_score_base": 9, "best_time_of_day": "evening",
        "best_season": ["Oct-May"], "accessibility": "easy",
        "editorial_summary": "Watch ancient Kathakali drama followed by high-energy Kalaripayattu martial arts performed by local masters.",
        "opening_hours": ["Monday-Sunday: 17:00-19:00"], "skip_if": "If you are not interested in traditional regional performing arts.",
        "insider_tip": "Arrive 30 minutes early to watch the Kathakali artists apply their intricate, natural face makeup.",
        "confidence_pct": 96
    },
    {
        "activity_id": "kundala_lake_munnar_08", "destination": "Munnar", "name": "Kundala Lake Pedal Boating",
        "category": "nature", "duration_minutes": 90, "cost_per_person": 200,
        "available_slots": ["09:00", "11:00", "14:00", "15:30"], "risk_level": "low",
        "tags": ["lake", "boating", "nature", "scenic"], "lat": 10.1333, "lng": 77.1833,
        "fatigue_score_base": 3, "morale_score_base": 7, "best_time_of_day": "morning",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "A peaceful lake surrounded by lush green valleys, famous for shikara boat rides and cherry blossoms.",
        "opening_hours": ["Monday-Sunday: 09:00-17:00"], "skip_if": "Rainy weather, as boats lack roof cover.",
        "insider_tip": "Try the Kashmiri-style Shikara boat for a relaxing, romantic glide along the pine-fringed banks.",
        "confidence_pct": 98
    },
    {
        "activity_id": "chinnar_safari_munnar_09", "destination": "Munnar", "name": "Chinnar Wildlife Sanctuary Walk",
        "category": "wildlife", "duration_minutes": 180, "cost_per_person": 300,
        "available_slots": ["07:00", "15:00"], "risk_level": "medium",
        "tags": ["wildlife", "nature", "trekking", "offbeat"], "lat": 10.3500, "lng": 77.1667,
        "fatigue_score_base": 5, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Oct-Mar"], "accessibility": "moderate",
        "editorial_summary": "A dry thorny forest sanctuary home to the endangered Grizzled Giant Squirrel.",
        "opening_hours": ["Monday-Sunday: 06:00-18:00"], "skip_if": "During dry summer months when forest fire risks are high.",
        "insider_tip": "Hire a local tribal guide for the river trek; they are excellent at spotting camouflaged chameleons.",
        "confidence_pct": 93
    },
    {
        "activity_id": "lockhart_gap_munnar_10", "destination": "Munnar", "name": "Lockhart Gap Viewpoint Sunset",
        "category": "nature", "duration_minutes": 60, "cost_per_person": 0,
        "available_slots": ["16:30", "17:00"], "risk_level": "low",
        "tags": ["nature", "viewpoint", "sunset", "clouds", "scenic"], "lat": 10.0450, "lng": 77.0980,
        "fatigue_score_base": 2, "morale_score_base": 8, "best_time_of_day": "evening",
        "best_season": ["Sep-May"], "accessibility": "easy",
        "editorial_summary": "A scenic gap in the hills offering a bird's eye view of Bishnu valley and misty winding highway roads.",
        "opening_hours": ["Monday-Sunday: 24 Hours"], "skip_if": "Overcast or heavy fog days when valley is hidden.",
        "insider_tip": "Sit on the roadside retaining wall with hot tea bought from the local stall to watch the clouds roll in.",
        "confidence_pct": 96
    },
    {
        "activity_id": "echo_point_munnar_11", "destination": "Munnar", "name": "Echo Point Lakeside scream",
        "category": "nature", "duration_minutes": 45, "cost_per_person": 20,
        "available_slots": ["09:00", "11:00", "15:00"], "risk_level": "low",
        "tags": ["nature", "lake", "scenic", "fun"], "lat": 10.1180, "lng": 77.1610,
        "fatigue_score_base": 2, "morale_score_base": 6, "best_time_of_day": "morning",
        "best_season": ["Oct-May"], "accessibility": "easy",
        "editorial_summary": "A meeting point of three mountain streams where screams echo clearly across the lake slopes.",
        "opening_hours": ["Monday-Sunday: 06:00-18:00"], "skip_if": "Heavily crowded weekend afternoons when echo gets lost in noise.",
        "insider_tip": "Arrive early morning when the air is still; the echo effect works best when the surroundings are quiet.",
        "confidence_pct": 98
    },
    {
        "activity_id": "rose_garden_munnar_12", "destination": "Munnar", "name": "Munnar Rose Garden Tour",
        "category": "nature", "duration_minutes": 60, "cost_per_person": 50,
        "available_slots": ["09:00", "11:00", "14:00", "16:00"], "risk_level": "low",
        "tags": ["nature", "garden", "flowers", "family"], "lat": 10.0765, "lng": 77.0788,
        "fatigue_score_base": 2, "morale_score_base": 6, "best_time_of_day": "morning",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "A beautiful terraced garden showcasing hundreds of rare varieties of roses, dahlias, and spices.",
        "opening_hours": ["Monday-Sunday: 10:00-17:00"], "skip_if": "Off-season (Monsoon), as many plants are not in bloom.",
        "insider_tip": "Great stopover for children and flower enthusiasts on the way to Madupetty Dam.",
        "confidence_pct": 95
    },
    {
        "activity_id": "marayoor_sandal_munnar_13", "destination": "Munnar", "name": "Marayoor Sandalwood Forest Drive",
        "category": "nature", "duration_minutes": 180, "cost_per_person": 0,
        "available_slots": ["09:00", "14:00"], "risk_level": "low",
        "tags": ["nature", "forest", "sandalwood", "scenic", "offbeat"], "lat": 10.2725, "lng": 77.1510,
        "fatigue_score_base": 3, "morale_score_base": 7, "best_time_of_day": "morning",
        "best_season": ["Oct-May"], "accessibility": "easy",
        "editorial_summary": "A scenic region featuring natural sandalwood forests, cave murals, and ancient stone dolmens.",
        "opening_hours": ["Monday-Sunday: 24 Hours"], "skip_if": "Nights, as forest roads can have wild elephant crossings.",
        "insider_tip": "Visit the government-run sandalwood store to buy authentic sandalwood oil and powders.",
        "confidence_pct": 93
    },
    {
        "activity_id": "elephant_park_munnar_14", "destination": "Munnar", "name": "Carmelagiri Elephant Park Ride",
        "category": "experience", "duration_minutes": 60, "cost_per_person": 500,
        "available_slots": ["09:00", "11:00", "14:00", "16:00"], "risk_level": "medium",
        "tags": ["experience", "elephant", "ride", "family"], "lat": 10.1005, "lng": 77.0850,
        "fatigue_score_base": 2, "morale_score_base": 5, "best_time_of_day": "afternoon",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "A private park offering short forest elephant rides and elephant-feeding experiences.",
        "opening_hours": ["Monday-Sunday: 09:00-17:00"], "skip_if": "Ethical concerns (if you prefer observing animals in the wild).",
        "insider_tip": "Skip the elephant ride and pay only for fruit baskets to feed the elephants; it's more interactive.",
        "confidence_pct": 94
    },
    {
        "activity_id": "attukad_falls_munnar_15", "destination": "Munnar", "name": "Attukad Waterfalls View & Bridge Walk",
        "category": "nature", "duration_minutes": 60, "cost_per_person": 0,
        "available_slots": ["08:30", "10:30", "15:00"], "risk_level": "low",
        "tags": ["nature", "waterfall", "bridge", "scenic"], "lat": 10.0653, "lng": 77.0425,
        "fatigue_score_base": 3, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Jun-Jan"], "accessibility": "moderate",
        "editorial_summary": "A roaring waterfall situated between Munnar and Pallivasal, reachable via a narrow hanging bridge.",
        "opening_hours": ["Monday-Sunday: 24 Hours"], "skip_if": "Peak dry summer (March-May) when the fall is almost dry.",
        "insider_tip": "The road to the waterfall is extremely narrow and steep. Better to walk down from the main highway turn.",
        "confidence_pct": 96
    },
    {
        "activity_id": "chinnakanal_falls_munnar_16", "destination": "Munnar", "name": "Chinnakanal Power House Waterfall",
        "category": "nature", "duration_minutes": 60, "cost_per_person": 0,
        "available_slots": ["09:00", "14:00", "16:00"], "risk_level": "low",
        "tags": ["nature", "waterfall", "scenic"], "lat": 10.0270, "lng": 77.1350,
        "fatigue_score_base": 2, "morale_score_base": 7, "best_time_of_day": "morning",
        "best_season": ["Jun-Feb"], "accessibility": "easy",
        "editorial_summary": "Cascades down a steep rock slope from Devikulam hill lake, offering a beautiful roadside vista.",
        "opening_hours": ["Monday-Sunday: 24 Hours"], "skip_if": "Monsoon floods, when spray blocks the road view.",
        "insider_tip": "Stop here for photos on your way to Suryanelli or Lockhart gap; the tea estates around are lovely.",
        "confidence_pct": 97
    },
    {
        "activity_id": "tea_estate_walk_munnar_17", "destination": "Munnar", "name": "Tata Tea Estate Walking Tour",
        "category": "nature", "duration_minutes": 90, "cost_per_person": 0,
        "available_slots": ["08:00", "16:00"], "risk_level": "low",
        "tags": ["nature", "tea_gardens", "walking", "photography"], "lat": 10.0880, "lng": 77.0600,
        "fatigue_score_base": 3, "morale_score_base": 9, "best_time_of_day": "morning",
        "best_season": ["Oct-May"], "accessibility": "easy",
        "editorial_summary": "Walk through the geometrically trimmed hedges of tea estates, smelling fresh tea leaves.",
        "opening_hours": ["Monday-Sunday: 24 Hours"], "skip_if": "Heavy rains or wet grass (which attracts leeches).",
        "insider_tip": "Wear long socks and carry a small pouch of salt to protect yourself from leeches.",
        "confidence_pct": 98
    },
    {
        "activity_id": "pothamedu_viewpoint_munnar_18", "destination": "Munnar", "name": "Pothamedu Viewpoint Tea & Cardamom Walk",
        "category": "nature", "duration_minutes": 90, "cost_per_person": 0,
        "available_slots": ["08:00", "16:30"], "risk_level": "low",
        "tags": ["nature", "viewpoint", "tea_gardens", "scenic"], "lat": 10.0750, "lng": 77.0450,
        "fatigue_score_base": 3, "morale_score_base": 8, "best_time_of_day": "evening",
        "best_season": ["Sep-May"], "accessibility": "easy",
        "editorial_summary": "A peaceful viewpoint showing wide valleys of tea, coffee, and cardamom plantations.",
        "opening_hours": ["Monday-Sunday: 24 Hours"], "skip_if": "Dense foggy days when everything is covered in white.",
        "insider_tip": "Great photography spot. Enjoy hot cardamom tea from the small roadside stalls.",
        "confidence_pct": 98
    },
    {
        "activity_id": "anamudi_view_munnar_19", "destination": "Munnar", "name": "Anamudi Peak Viewpoint Stop",
        "category": "nature", "duration_minutes": 45, "cost_per_person": 0,
        "available_slots": ["09:00", "11:00", "14:00"], "risk_level": "low",
        "tags": ["nature", "viewpoint", "mountains", "scenic"], "lat": 10.1667, "lng": 77.0667,
        "fatigue_score_base": 2, "morale_score_base": 7, "best_time_of_day": "morning",
        "best_season": ["Oct-May"], "accessibility": "easy",
        "editorial_summary": "Observe South India's highest mountain peak, towering at 2,695 meters above sea level.",
        "opening_hours": ["Monday-Sunday: 24 Hours"], "skip_if": "Rainy seasons when peak is constantly hidden in storm clouds.",
        "insider_tip": "The peak is inside Eravikulam National Park. You can view it from the safari bus path.",
        "confidence_pct": 97
    },
    {
        "activity_id": "attukal_trek_munnar_20", "destination": "Munnar", "name": "Attukal Forest Trekking",
        "category": "adventure", "duration_minutes": 180, "cost_per_person": 800,
        "available_slots": ["08:00", "14:00"], "risk_level": "medium",
        "tags": ["adventure", "trekking", "forest", "nature"], "lat": 10.0600, "lng": 77.0350,
        "fatigue_score_base": 6, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Oct-Mar"], "accessibility": "difficult",
        "editorial_summary": "A guided forest trek through wild hills, tea margins, and gushing freshwater streams.",
        "opening_hours": ["Monday-Sunday: 08:00-16:00"], "skip_if": "Peak monsoon (heavy mud tracks and river crossings are dangerous).",
        "insider_tip": "Wear good boots and pack an extra set of dry clothes in your waterproof daypack.",
        "confidence_pct": 91
    }
]

# --- LEH (20 Activities) ---
leh_activities = [
    {
        "activity_id": "leh_palace_leh_01", "destination": "Leh", "name": "Leh Palace Heritage Tour",
        "category": "cultural", "duration_minutes": 90, "cost_per_person": 250,
        "available_slots": ["09:00", "11:00", "14:30", "16:00"], "risk_level": "low",
        "tags": ["heritage", "palace", "history", "viewpoint"], "lat": 34.1565, "lng": 77.5855,
        "fatigue_score_base": 4, "morale_score_base": 7, "best_time_of_day": "afternoon",
        "best_season": ["Jun-Sep"], "accessibility": "moderate",
        "editorial_summary": "A nine-story medieval palace built by King Sengge Namgyal, looking like a miniature Potala Palace.",
        "opening_hours": ["Monday-Sunday: 08:00-18:00"], "skip_if": "First day of arrival; you must rest to avoid high altitude sickness.",
        "insider_tip": "Climb to the upper roof platform for a stunning panoramic view of Leh city and the Zanskar range.",
        "confidence_pct": 98
    },
    {
        "activity_id": "shanti_stupa_leh_02", "destination": "Leh", "name": "Shanti Stupa Sunset Visit",
        "category": "spiritual", "duration_minutes": 90, "cost_per_person": 0,
        "available_slots": ["16:30", "17:30"], "risk_level": "low",
        "tags": ["spiritual", "stupa", "sunset", "viewpoint", "buddhism"], "lat": 34.1678, "lng": 77.5739,
        "fatigue_score_base": 3, "morale_score_base": 9, "best_time_of_day": "evening",
        "best_season": ["Jun-Sep"], "accessibility": "easy",
        "editorial_summary": "A white-domed Buddhist monument built by Japanese monks, offering spectacular sunset views.",
        "opening_hours": ["Monday-Sunday: 05:00-21:00"], "skip_if": "Overcast evenings.",
        "insider_tip": "You can drive up to the parking lot or climb the 500 steep concrete steps from Changspa road.",
        "confidence_pct": 99
    },
    {
        "activity_id": "hall_of_fame_leh_03", "destination": "Leh", "name": "Indian Army Hall of Fame Museum",
        "category": "cultural", "duration_minutes": 120, "cost_per_person": 200,
        "available_slots": ["09:00", "11:00", "14:30", "16:00"], "risk_level": "low",
        "tags": ["museum", "history", "military", "patriotic"], "lat": 34.1442, "lng": 77.5348,
        "fatigue_score_base": 2, "morale_score_base": 8, "best_time_of_day": "afternoon",
        "best_season": ["Jun-Sep"], "accessibility": "easy",
        "editorial_summary": "A war memorial and museum built by the Indian Army, honoring soldiers who lost their lives in wars.",
        "opening_hours": ["Monday-Sunday: 09:00-13:00, 14:00-19:00"], "skip_if": "If you are not interested in military history.",
        "insider_tip": "Stay for the 15-minute documentary film on the Siachen glacier operations shown in the gallery hall.",
        "confidence_pct": 98
    },
    {
        "activity_id": "magnetic_hill_leh_04", "destination": "Leh", "name": "Magnetic Hill Optical Illusion",
        "category": "nature", "duration_minutes": 45, "cost_per_person": 0,
        "available_slots": ["09:00", "11:00", "14:00", "15:30"], "risk_level": "low",
        "tags": ["nature", "gravity", "illusion", "scenic", "roadtrip"], "lat": 34.1689, "lng": 77.3486,
        "fatigue_score_base": 1, "morale_score_base": 6, "best_time_of_day": "morning",
        "best_season": ["Jun-Sep"], "accessibility": "easy",
        "editorial_summary": "A gravity hill road where the layout of surrounding slopes creates an optical illusion that cars roll uphill.",
        "opening_hours": ["Monday-Sunday: 24 Hours"], "skip_if": "Heavy snow, which covers the road markers.",
        "insider_tip": "Put your vehicle in neutral within the marked yellow box on the road and watch it appear to roll.",
        "confidence_pct": 98
    },
    {
        "activity_id": "sangam_view_leh_05", "destination": "Leh", "name": "Sangam Indus & Zanskar River Confluence",
        "category": "nature", "duration_minutes": 90, "cost_per_person": 0,
        "available_slots": ["09:00", "11:30", "14:00", "15:30"], "risk_level": "low",
        "tags": ["nature", "river", "scenic", "rafting", "photography"], "lat": 34.1658, "lng": 77.2486,
        "fatigue_score_base": 2, "morale_score_base": 9, "best_time_of_day": "morning",
        "best_season": ["Jun-Sep"], "accessibility": "easy",
        "editorial_summary": "Observe the muddy waters of the Zanskar River merging with the shiny green Indus River.",
        "opening_hours": ["Monday-Sunday: 24 Hours"], "skip_if": "None; the color difference is visible year-round, except when frozen.",
        "insider_tip": "Walk down to the river bank. This is also the endpoint for the famous Zanskar rafting expedition.",
        "confidence_pct": 99
    },
    {
        "activity_id": "pathar_sahib_leh_06", "destination": "Leh", "name": "Gurudwara Pathar Sahib Visit",
        "category": "spiritual", "duration_minutes": 60, "cost_per_person": 0,
        "available_slots": ["09:00", "12:00", "15:00"], "risk_level": "low",
        "tags": ["spiritual", "gurudwara", "sikhism", "history"], "lat": 34.1755, "lng": 77.4111,
        "fatigue_score_base": 2, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Jun-Sep"], "accessibility": "easy",
        "editorial_summary": "A beautiful Sikh shrine built around a boulder believed to bear the imprint of Guru Nanak.",
        "opening_hours": ["Monday-Sunday: 06:00-21:00"], "skip_if": "Dress code: cover your head and remove shoes before entering.",
        "insider_tip": "Enjoy the hot sweet tea and freshly prepared langar food served by the army troops.",
        "confidence_pct": 98
    },
    {
        "activity_id": "thiksey_monastery_leh_07", "destination": "Leh", "name": "Thiksey Monastery Morning Prayers",
        "category": "spiritual", "duration_minutes": 120, "cost_per_person": 50,
        "available_slots": ["06:00", "09:00", "14:00"], "risk_level": "low",
        "tags": ["spiritual", "monastery", "buddhism", "culture", "viewpoint"], "lat": 34.0560, "lng": 77.6667,
        "fatigue_score_base": 4, "morale_score_base": 9, "best_time_of_day": "morning",
        "best_season": ["Jun-Sep"], "accessibility": "moderate",
        "editorial_summary": "A twelve-story complex resembling Lhasa's Potala, housing a 15-meter-tall statue of Maitreya Buddha.",
        "opening_hours": ["Monday-Sunday: 06:00-18:00"], "skip_if": "If you struggle with altitude stairs (monastery has steep climb steps).",
        "insider_tip": "Arrive by 6:00 AM to sit with the monks during their rhythmic morning prayers and chantings.",
        "confidence_pct": 99
    },
    {
        "activity_id": "hemis_monastery_leh_08", "destination": "Leh", "name": "Hemis Monastery & Museum Tour",
        "category": "cultural", "duration_minutes": 120, "cost_per_person": 100,
        "available_slots": ["09:00", "11:00", "14:00", "15:30"], "risk_level": "low",
        "tags": ["heritage", "monastery", "buddhism", "museum"], "lat": 33.9128, "lng": 77.8010,
        "fatigue_score_base": 3, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Jun-Sep"], "accessibility": "easy",
        "editorial_summary": "Ladakh's wealthiest and largest monastery, tucked away in a mountain canyon, famous for its mask festival.",
        "opening_hours": ["Monday-Sunday: 08:00-13:00, 14:00-18:00"], "skip_if": "During winter months when access passes might freeze.",
        "insider_tip": "Visit the subterranean museum, which houses an extraordinary collection of ancient thangkas and gold weapons.",
        "confidence_pct": 98
    },
    {
        "activity_id": "pangong_lake_leh_09", "destination": "Leh", "name": "Pangong Tso Lake Overnight Excursion",
        "category": "nature", "duration_minutes": 1440, "cost_per_person": 2500,
        "available_slots": ["07:00"], "risk_level": "high",
        "tags": ["nature", "lake", "camping", "scenic", "offbeat"], "lat": 33.7275, "lng": 78.4611,
        "fatigue_score_base": 8, "morale_score_base": 10, "best_time_of_day": "any",
        "best_season": ["Jun-Sep"], "accessibility": "difficult",
        "editorial_summary": "A high-altitude endorheic lake stretching from India to Tibet, shifting colors from turquoise to deep blue.",
        "opening_hours": ["Monday-Sunday: 24 Hours"], "skip_if": "Failing to acquire the mandatory Inner Line Permit (ILP) first.",
        "insider_tip": "Stay overnight in wooden cottages at Spangmik or Merak to see the raw Milky Way night sky.",
        "confidence_pct": 97
    },
    {
        "activity_id": "khardungla_pass_leh_10", "destination": "Leh", "name": "Khardung La Pass High Altitude Crossing",
        "category": "adventure", "duration_minutes": 60, "cost_per_person": 0,
        "available_slots": ["08:00", "11:00", "14:00"], "risk_level": "high",
        "tags": ["adventure", "pass", "snow", "roadtrip", "scenic"], "lat": 34.2789, "lng": 77.6047,
        "fatigue_score_base": 6, "morale_score_base": 9, "best_time_of_day": "morning",
        "best_season": ["Jun-Sep"], "accessibility": "difficult",
        "editorial_summary": "One of the highest motorable mountain passes in the world, standing at 5,359 meters.",
        "opening_hours": ["Monday-Sunday: 24 Hours"], "skip_if": "Having asthma or low oxygen symptoms; do not stay at the pass for over 20 minutes.",
        "insider_tip": "Drink plenty of water before the ascent. Buy hot noodles and black tea at the Army canteen at the top.",
        "confidence_pct": 98
    },
    {
        "activity_id": "nubra_camel_leh_11", "destination": "Leh", "name": "Bactrian Camel Ride at Hunder Dunes",
        "category": "experience", "duration_minutes": 60, "cost_per_person": 500,
        "available_slots": ["09:00", "16:30", "17:30"], "risk_level": "medium",
        "tags": ["experience", "camel", "desert", "dunes", "scenic"], "lat": 34.5800, "lng": 77.4333,
        "fatigue_score_base": 3, "morale_score_base": 8, "best_time_of_day": "evening",
        "best_season": ["Jun-Sep"], "accessibility": "easy",
        "editorial_summary": "Ride rare double-humped Bactrian camels through the high-altitude sand dunes of Nubra Valley.",
        "opening_hours": ["Monday-Sunday: 09:00-19:00"], "skip_if": "None; the camel rides run daily in summer.",
        "insider_tip": "Wear long trousers to protect your legs from camel hair. The evening sunset light is best for photos.",
        "confidence_pct": 95
    },
    {
        "activity_id": "diskit_monastery_leh_12", "destination": "Leh", "name": "Diskit Monastery & Giant Buddha",
        "category": "cultural", "duration_minutes": 90, "cost_per_person": 50,
        "available_slots": ["09:00", "11:00", "14:00", "16:00"], "risk_level": "low",
        "tags": ["heritage", "monastery", "buddhism", "scenic"], "lat": 34.5902, "lng": 77.4285,
        "fatigue_score_base": 4, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Jun-Sep"], "accessibility": "moderate",
        "editorial_summary": "The oldest and largest monastery in Nubra Valley, featuring a giant 32-meter statue of Maitreya Buddha.",
        "opening_hours": ["Monday-Sunday: 07:00-18:00"], "skip_if": "None; the site is easily accessible via road.",
        "insider_tip": "Walk around the base of the giant Buddha statue; the view of the Shyok river valley from there is unmatched.",
        "confidence_pct": 98
    },
    {
        "activity_id": "tsomoriri_lake_leh_13", "destination": "Leh", "name": "Tso Moriri Lake Remote Exploration",
        "category": "nature", "duration_minutes": 1440, "cost_per_person": 2000,
        "available_slots": ["07:00"], "risk_level": "high",
        "tags": ["nature", "lake", "offbeat", "scenic", "camping"], "lat": 32.9000, "lng": 78.3200,
        "fatigue_score_base": 9, "morale_score_base": 8, "best_time_of_day": "any",
        "best_season": ["Jun-Sep"], "accessibility": "difficult",
        "editorial_summary": "A pristine wetland reserve lake, less commercialized than Pangong, surrounded by snow peaks.",
        "opening_hours": ["Monday-Sunday: 24 Hours"], "skip_if": "If you suffer from cold sensitivity, as nights get freezing even in July.",
        "insider_tip": "Stay in local homestays in Korzok village to support the Ladakhi community and experience local life.",
        "confidence_pct": 92
    },
    {
        "activity_id": "spituk_monastery_leh_14", "destination": "Leh", "name": "Spituk Monastery Hill Visit",
        "category": "spiritual", "duration_minutes": 90, "cost_per_person": 30,
        "available_slots": ["09:00", "11:00", "14:30", "16:00"], "risk_level": "low",
        "tags": ["spiritual", "monastery", "viewpoint", "buddhism"], "lat": 34.1299, "lng": 77.5255,
        "fatigue_score_base": 3, "morale_score_base": 7, "best_time_of_day": "morning",
        "best_season": ["Jun-Sep"], "accessibility": "easy",
        "editorial_summary": "An 11th-century monastery perched on a hill, overlooking the Leh airport runway strip.",
        "opening_hours": ["Monday-Sunday: 08:00-18:00"], "skip_if": "None; very close to Leh city center.",
        "insider_tip": "Great spot for aviation geeks; you can capture unique photos of flights landing amidst mountains.",
        "confidence_pct": 97
    },
    {
        "activity_id": "old_town_walk_leh_15", "destination": "Leh", "name": "Leh Old Town Heritage Walking Tour",
        "category": "cultural", "duration_minutes": 120, "cost_per_person": 0,
        "available_slots": ["09:00", "16:00"], "risk_level": "low",
        "tags": ["heritage", "walking", "architecture", "history"], "lat": 34.1550, "lng": 77.5840,
        "fatigue_score_base": 4, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Jun-Sep"], "accessibility": "moderate",
        "editorial_summary": "Walk through mud-brick alleyways under Leh Palace, discovering old mosques, bakeries, and water mills.",
        "opening_hours": ["Monday-Sunday: 24 Hours"], "skip_if": "During the midday heat; morning or late evening is preferred.",
        "insider_tip": "Visit the Lala's Cafe, a restored traditional house, for a cup of hot sea buckthorn juice.",
        "confidence_pct": 93
    },
    {
        "activity_id": "shey_palace_leh_16", "destination": "Leh", "name": "Shey Palace & Copper Buddha Tour",
        "category": "cultural", "duration_minutes": 90, "cost_per_person": 30,
        "available_slots": ["09:00", "11:00", "14:00", "16:00"], "risk_level": "low",
        "tags": ["heritage", "palace", "buddhism", "history"], "lat": 34.0722, "lng": 77.6360,
        "fatigue_score_base": 3, "morale_score_base": 7, "best_time_of_day": "morning",
        "best_season": ["Jun-Sep"], "accessibility": "easy",
        "editorial_summary": "The former summer capital of Ladakh, housing a massive seated Shakyamuni Buddha made of gilded copper.",
        "opening_hours": ["Monday-Sunday: 08:00-18:00"], "skip_if": "None; located directly on the main highway road to Thiksey.",
        "insider_tip": "Walk up to the ruined fortress above the palace for a panoramic view of the Indus valley farming fields.",
        "confidence_pct": 98
    },
    {
        "activity_id": "alchi_temple_leh_17", "destination": "Leh", "name": "Alchi Temple Kashmiri-Style Murals",
        "category": "cultural", "duration_minutes": 120, "cost_per_person": 50,
        "available_slots": ["09:30", "12:00", "14:30"], "risk_level": "low",
        "tags": ["heritage", "temple", "buddhism", "art", "history"], "lat": 34.2233, "lng": 77.1752,
        "fatigue_score_base": 2, "morale_score_base": 8, "best_time_of_day": "afternoon",
        "best_season": ["Jun-Sep"], "accessibility": "easy",
        "editorial_summary": "An ancient temple enclave situated on the flat river plains, famous for its unique Kashmiri-style wall paintings.",
        "opening_hours": ["Monday-Sunday: 08:00-18:00"], "skip_if": "Photography is strictly prohibited inside the main dark shrine rooms.",
        "insider_tip": "Carry a small flashlight or use your phone light to appreciate the hyper-detailed wood carvings.",
        "confidence_pct": 95
    },
    {
        "activity_id": "likir_monastery_leh_18", "destination": "Leh", "name": "Likir Monastery & Golden Buddha",
        "category": "cultural", "duration_minutes": 90, "cost_per_person": 50,
        "available_slots": ["09:00", "11:00", "14:00", "15:30"], "risk_level": "low",
        "tags": ["heritage", "monastery", "buddhism", "viewpoint"], "lat": 34.2933, "lng": 77.2155,
        "fatigue_score_base": 3, "morale_score_base": 7, "best_time_of_day": "morning",
        "best_season": ["Jun-Sep"], "accessibility": "easy",
        "editorial_summary": "Famous for its massive 23-meter-tall outdoor gilded statue of Maitreya Buddha standing in open air.",
        "opening_hours": ["Monday-Sunday: 08:00-17:00"], "skip_if": "None; easy detour off the Leh-Srinagar highway.",
        "insider_tip": "There is a small clay pottery workshop run by local monks at the foot of the monastery.",
        "confidence_pct": 96
    },
    {
        "activity_id": "stock_palace_leh_19", "destination": "Leh", "name": "Stok Palace Royal Museum Tour",
        "category": "cultural", "duration_minutes": 120, "cost_per_person": 150,
        "available_slots": ["09:00", "11:00", "14:00", "16:00"], "risk_level": "low",
        "tags": ["heritage", "palace", "museum", "royalty"], "lat": 34.0722, "lng": 77.5683,
        "fatigue_score_base": 3, "morale_score_base": 7, "best_time_of_day": "afternoon",
        "best_season": ["Jun-Sep"], "accessibility": "easy",
        "editorial_summary": "The current residence of Ladakh's royal family, housing royal crowns, jewelry, and ancient thangkas.",
        "opening_hours": ["Monday-Sunday: 09:00-17:00"], "skip_if": "If you have already visited Leh Palace and prefer ruins over intact museums.",
        "insider_tip": "Visit the palace cafe for local barley flour pancakes and tea in the central courtyard.",
        "confidence_pct": 96
    },
    {
        "activity_id": "bazaar_shopping_leh_20", "destination": "Leh", "name": "Leh Main Bazaar Souvenir Shopping",
        "category": "shopping", "duration_minutes": 120, "cost_per_person": 0,
        "available_slots": ["10:30", "14:30", "17:00", "19:00"], "risk_level": "low",
        "tags": ["shopping", "bazaar", "crafts", "family"], "lat": 34.1539, "lng": 77.5828,
        "fatigue_score_base": 2, "morale_score_base": 7, "best_time_of_day": "evening",
        "best_season": ["Jun-Sep"], "accessibility": "easy",
        "editorial_summary": "A pedestrian-only street lined with shops selling apricot jams, pashmina shawls, and Tibetan prayer wheels.",
        "opening_hours": ["Monday-Sunday: 10:00-21:00"], "skip_if": "Sundays, when many shops are closed.",
        "insider_tip": "Buy dried apricots and sea buckthorn juices from the local women cooperatives sitting along the streets.",
        "confidence_pct": 98
    }
]

# --- MUMBAI (20 Activities) ---
mumbai_activities = [
    {
        "activity_id": "gateway_mumbai_01", "destination": "Mumbai", "name": "Gateway of India & Taj Palace Photo Stop",
        "category": "cultural", "duration_minutes": 45, "cost_per_person": 0,
        "available_slots": ["07:30", "09:00", "16:00", "17:30", "19:00"], "risk_level": "low",
        "tags": ["heritage", "monument", "architecture", "coast", "photography"], "lat": 18.9220, "lng": 72.8347,
        "fatigue_score_base": 2, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "Mumbai's most famous archway monument built in 1924, overlooking the Arabian Sea.",
        "opening_hours": ["Monday-Sunday: 24 Hours"], "skip_if": "Extreme monsoon downpours when high tides splash over the promenade.",
        "insider_tip": "Visit at sunrise (6:30 AM) to see the structure bathed in golden light without any crowds.",
        "confidence_pct": 99
    },
    {
        "activity_id": "elephanta_caves_mumbai_02", "destination": "Mumbai", "name": "Elephanta Caves Ferry & Tour",
        "category": "cultural", "duration_minutes": 240, "cost_per_person": 300,
        "available_slots": ["09:00", "11:00", "13:00"], "risk_level": "medium",
        "tags": ["heritage", "caves", "ferry", "history", "spiritual"], "lat": 18.9633, "lng": 72.9314,
        "fatigue_score_base": 5, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Oct-Mar"], "accessibility": "moderate",
        "editorial_summary": "Take a scenic ferry from the Gateway of India to an island containing rock-cut cave temples dedicated to Shiva.",
        "opening_hours": ["Tuesday-Sunday: 09:00-17:30"], "skip_if": "Mondays, when the caves are closed. Also skip during rough sea conditions.",
        "insider_tip": "Buy a return ferry ticket on the upper deck (costs ₹10 extra) for better breeze and views.",
        "confidence_pct": 98
    },
    {
        "activity_id": "marine_drive_mumbai_03", "destination": "Mumbai", "name": "Marine Drive Promenade Sunset Walk",
        "category": "nature", "duration_minutes": 90, "cost_per_person": 0,
        "available_slots": ["17:00", "18:30", "20:00"], "risk_level": "low",
        "tags": ["sunset", "promenade", "ocean", "scenic", "relaxed"], "lat": 18.9400, "lng": 72.8200,
        "fatigue_score_base": 2, "morale_score_base": 9, "best_time_of_day": "evening",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "A 3km long arc-shaped sea boulevard, also known as the Queen's Necklace due to its shape under streetlights.",
        "opening_hours": ["Monday-Sunday: 24 Hours"], "skip_if": "Heavy midday sun (there is no shade along the walk).",
        "insider_tip": "Grab a hot paper-cup chai from the mobile tea cycle vendors and sit on the concrete tetrapods.",
        "confidence_pct": 99
    },
    {
        "activity_id": "cst_station_mumbai_04", "destination": "Mumbai", "name": "Chhatrapati Shivaji Terminus (CST) Light Tour",
        "category": "cultural", "duration_minutes": 60, "cost_per_person": 0,
        "available_slots": ["09:00", "11:00", "15:00", "19:30"], "risk_level": "low",
        "tags": ["heritage", "architecture", "gothic", "history"], "lat": 18.9400, "lng": 72.8353,
        "fatigue_score_base": 2, "morale_score_base": 8, "best_time_of_day": "evening",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "A spectacular Gothic revival railway terminal and UNESCO site, bustling with suburban commuters.",
        "opening_hours": ["Monday-Sunday: 24 Hours"], "skip_if": "If you are highly claustrophobic during peak office commute hours (8-10 AM, 5-7 PM).",
        "insider_tip": "View the building from the pedestrian bridge across the street at 8 PM when it glows under yellow and red display lights.",
        "confidence_pct": 99
    },
    {
        "activity_id": "haji_ali_mumbai_05", "destination": "Mumbai", "name": "Haji Ali Dargah Causeway Walk",
        "category": "spiritual", "duration_minutes": 90, "cost_per_person": 0,
        "available_slots": ["08:30", "10:30", "15:00", "17:00"], "risk_level": "medium",
        "tags": ["spiritual", "mosque", "causeway", "ocean", "culture"], "lat": 18.9827, "lng": 72.8089,
        "fatigue_score_base": 3, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Oct-Mar"], "accessibility": "moderate",
        "editorial_summary": "A floating mosque and tomb of saint Haji Ali, connected to the shoreline by a narrow walk path.",
        "opening_hours": ["Monday-Sunday: 06:00-22:00"], "skip_if": "High tide, when the causeway pathway is completely submerged under water.",
        "insider_tip": "Check the local tide timetable online before walking. Wear modest clothes that cover limbs.",
        "confidence_pct": 98
    },
    {
        "activity_id": "chowpatty_food_mumbai_06", "destination": "Mumbai", "name": "Girgaon Chowpatty Street Food Tasting",
        "category": "food", "duration_minutes": 90, "cost_per_person": 250,
        "available_slots": ["17:30", "19:00", "20:30"], "risk_level": "low",
        "tags": ["food", "street_food", "beach", "local"], "lat": 18.9515, "lng": 72.8155,
        "fatigue_score_base": 2, "morale_score_base": 8, "best_time_of_day": "evening",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "Dine on the sand at Girgaon beach, tasting spicy pav bhaji, bhel puri, and kulfi ice cream.",
        "opening_hours": ["Monday-Sunday: 12:00-23:59"], "skip_if": "None; beach is active even during monsoons, though stalls have canvas covers.",
        "insider_tip": "Try the famous spicy Ragda Pattice and sweet Kulfi at stall 12 (Sharmaji's).",
        "confidence_pct": 97
    },
    {
        "activity_id": "colaba_causeway_mumbai_07", "destination": "Mumbai", "name": "Colaba Causeway Street Shopping",
        "category": "shopping", "duration_minutes": 120, "cost_per_person": 0,
        "available_slots": ["11:00", "14:00", "17:00", "19:00"], "risk_level": "low",
        "tags": ["shopping", "bazaar", "crafts", "cafes"], "lat": 18.9215, "lng": 72.8315,
        "fatigue_score_base": 3, "morale_score_base": 7, "best_time_of_day": "evening",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "A busy commercial street market selling cheap antique brasswares, apparel, beads, and street bags.",
        "opening_hours": ["Monday-Saturday: 10:00-21:00 (Sundays closed/partially active)"], "skip_if": "If you struggle with persistent street sellers.",
        "insider_tip": "Stop at the historic Leopold Cafe or Cafe Mondegar along the street for a cold beer and beef chili.",
        "confidence_pct": 98
    },
    {
        "activity_id": "crawford_market_mumbai_08", "destination": "Mumbai", "name": "Crawford Market Wholesale Shopping",
        "category": "shopping", "duration_minutes": 90, "cost_per_person": 0,
        "available_slots": ["11:00", "14:00", "16:00"], "risk_level": "low",
        "tags": ["shopping", "bazaar", "wholesale", "history"], "lat": 18.9472, "lng": 72.8344,
        "fatigue_score_base": 4, "morale_score_base": 6, "best_time_of_day": "afternoon",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "A historic indoor market designed in Norman-Gothic style, selling wholesale fruits, dry foods, and home items.",
        "opening_hours": ["Monday-Saturday: 11:00-20:00"], "skip_if": "Sundays, when the main wholesale indoor section is closed.",
        "insider_tip": "Carry cash; cards and digital wallets are rarely accepted by wholesale vendors.",
        "confidence_pct": 96
    },
    {
        "activity_id": "sanjay_gandhi_mumbai_09", "destination": "Mumbai", "name": "Sanjay Gandhi National Park Safari",
        "category": "wildlife", "duration_minutes": 240, "cost_per_person": 250,
        "available_slots": ["09:00", "11:00", "14:00"], "risk_level": "medium",
        "tags": ["wildlife", "safari", "nature", "forest", "caves"], "lat": 19.2215, "lng": 72.9150,
        "fatigue_score_base": 5, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Oct-May"], "accessibility": "easy",
        "editorial_summary": "A vast green national park situated inside Mumbai city limits, featuring leopard safaris and cycling trails.",
        "opening_hours": ["Tuesday-Sunday: 07:30-17:30"], "skip_if": "Mondays, when park gates are locked.",
        "insider_tip": "Rent a bicycle at the entry gate to ride the scenic 5km paved forest road to Kanheri Caves.",
        "confidence_pct": 95
    },
    {
        "activity_id": "kanheri_caves_mumbai_10", "destination": "Mumbai", "name": "Kanheri Caves Buddhist Rock-Cut Exploration",
        "category": "cultural", "duration_minutes": 120, "cost_per_person": 25,
        "available_slots": ["09:30", "11:30", "14:30"], "risk_level": "low",
        "tags": ["heritage", "caves", "buddhism", "history", "trekking"], "lat": 19.2062, "lng": 72.9067,
        "fatigue_score_base": 4, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Oct-Mar"], "accessibility": "moderate",
        "editorial_summary": "Over a hundred ancient Buddhist caves carved out of basaltic rock, dating back to the 1st century BC.",
        "opening_hours": ["Tuesday-Sunday: 07:30-17:00"], "skip_if": "Heavily rainy days when paths are muddy and slippery.",
        "insider_tip": "Climb Cave 3 to see the massive 5-meter tall carved figures of standing Buddhas on the entrance columns.",
        "confidence_pct": 98
    },
    {
        "activity_id": "bandra_sealink_mumbai_11", "destination": "Mumbai", "name": "Bandra Fort Sealink Sunset View",
        "category": "nature", "duration_minutes": 60, "cost_per_person": 0,
        "available_slots": ["16:30", "17:30"], "risk_level": "low",
        "tags": ["sunset", "viewpoint", "bridge", "photography"], "lat": 19.0418, "lng": 72.8189,
        "fatigue_score_base": 2, "morale_score_base": 8, "best_time_of_day": "evening",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "Watch sunset from the ruins of Castella de Aguada (Bandra Fort) overlooking the Bandra-Worli Sea Link bridge.",
        "opening_hours": ["Monday-Sunday: 06:00-18:30"], "skip_if": "Overcast or stormy evenings.",
        "insider_tip": "The park path is crowded; walk down to the rocky beach strip below the fort walls for a clear photo frame.",
        "confidence_pct": 98
    },
    {
        "activity_id": "siddhivinayak_mumbai_12", "destination": "Mumbai", "name": "Siddhivinayak Ganesha Temple Tour",
        "category": "spiritual", "duration_minutes": 90, "cost_per_person": 0,
        "available_slots": ["06:00", "09:30", "14:00", "17:00"], "risk_level": "low",
        "tags": ["spiritual", "temple", "hinduism", "culture"], "lat": 19.0168, "lng": 72.8300,
        "fatigue_score_base": 3, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "A grand, multi-tiered Hindu temple dedicated to Lord Ganesha, attracting millions of local devotees.",
        "opening_hours": ["Monday-Sunday: 05:30-22:00"], "skip_if": "Tuesdays (which are highly crowded and queue times can reach 3-4 hours).",
        "insider_tip": "Pay for a 'Quick Darshan' pass online or at counters if you want to skip the general public crawl lanes.",
        "confidence_pct": 97
    },
    {
        "activity_id": "hanging_gardens_mumbai_13", "destination": "Mumbai", "name": "Hanging Gardens & Old Woman's Shoe",
        "category": "nature", "duration_minutes": 60, "cost_per_person": 0,
        "available_slots": ["09:00", "16:00", "17:30"], "risk_level": "low",
        "tags": ["nature", "garden", "scenic", "family"], "lat": 18.9568, "lng": 72.8055,
        "fatigue_score_base": 2, "morale_score_base": 6, "best_time_of_day": "morning",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "Terraced gardens on Malabar Hill, featuring animal-shaped hedges and a giant stone boot replica.",
        "opening_hours": ["Monday-Sunday: 05:00-21:00"], "skip_if": "If you are looking for complex botanical collections.",
        "insider_tip": "Cross the street to the Kamla Nehru Park viewing platform for an amazing vista of Marine Drive curve.",
        "confidence_pct": 96
    },
    {
        "activity_id": "museum_csmvs_mumbai_14", "destination": "Mumbai", "name": "CSMVS Prince of Wales Museum Tour",
        "category": "cultural", "duration_minutes": 150, "cost_per_person": 150,
        "available_slots": ["10:30", "13:00", "15:00"], "risk_level": "low",
        "tags": ["museum", "heritage", "history", "arts", "family"], "lat": 18.9269, "lng": 72.8327,
        "fatigue_score_base": 3, "morale_score_base": 9, "best_time_of_day": "afternoon",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "A grand heritage dome museum showcasing art, natural history, and archaeological relics.",
        "opening_hours": ["Monday-Sunday: 10:15-18:00"], "skip_if": "If you don't enjoy galleries or museum audio guides.",
        "insider_tip": "Rent the audio guide; the descriptions of ancient Harappan pottery and Buddhist relics are highly detailed.",
        "confidence_pct": 98
    },
    {
        "activity_id": "dhobi_ghat_mumbai_15", "destination": "Mumbai", "name": "Dhobi Ghat Mahalaxmi Laundry Viewpoint",
        "category": "cultural", "duration_minutes": 45, "cost_per_person": 0,
        "available_slots": ["09:00", "11:00", "14:00"], "risk_level": "low",
        "tags": ["heritage", "laundry", "history", "photography", "local"], "lat": 18.9822, "lng": 72.8253,
        "fatigue_score_base": 1, "morale_score_base": 6, "best_time_of_day": "morning",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "The world's largest open-air laundry, where thousands of dhobis scrub clothes in open concrete wash pens.",
        "opening_hours": ["Monday-Sunday: 24 Hours"], "skip_if": "Avoid walking inside the dirty alleys unless with a registered local guide.",
        "insider_tip": "The best view is from the bridge right next to Mahalaxmi Railway Station exit.",
        "confidence_pct": 98
    },
    {
        "activity_id": "prithvi_theatre_mumbai_16", "destination": "Mumbai", "name": "Prithvi Theatre Show & Cafe Visit",
        "category": "experience", "duration_minutes": 150, "cost_per_person": 500,
        "available_slots": ["18:00", "20:00"], "risk_level": "low",
        "tags": ["experience", "drama", "arts", "cafes", "nightlife"], "lat": 19.1062, "lng": 72.8258,
        "fatigue_score_base": 2, "morale_score_base": 9, "best_time_of_day": "night",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "Mumbai's legendary home of experimental theater, featuring an iconic outdoor Irish coffee cafe.",
        "opening_hours": ["Tuesday-Sunday: 11:00-23:00"], "skip_if": "Mondays, when the theater has no shows scheduled.",
        "insider_tip": "Order their hot cutting chai and famous apple pie at the outdoor cafe while waiting for the play.",
        "confidence_pct": 94
    },
    {
        "activity_id": "dharavi_tour_mumbai_17", "destination": "Mumbai", "name": "Dharavi Educational Walking Tour",
        "category": "experience", "duration_minutes": 120, "cost_per_person": 600,
        "available_slots": ["09:30", "14:30"], "risk_level": "low",
        "tags": ["experience", "walking", "industry", "ethical"], "lat": 19.0380, "lng": 72.8538,
        "fatigue_score_base": 4, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Oct-Mar"], "accessibility": "moderate",
        "editorial_summary": "An ethical tour showcasing Dharavi's thriving recycling, leather, and pottery home industries.",
        "opening_hours": ["Monday-Saturday: 09:00-17:00"], "skip_if": "Sundays, when most local home workshops are closed.",
        "insider_tip": "Book with operators like Reality Tours that reinvest profits back into local community education schools.",
        "confidence_pct": 93
    },
    {
        "activity_id": "chor_bazaar_mumbai_18", "destination": "Mumbai", "name": "Chor Bazaar Vintage Antiquing",
        "category": "shopping", "duration_minutes": 90, "cost_per_person": 0,
        "available_slots": ["11:00", "14:00", "16:00"], "risk_level": "low",
        "tags": ["shopping", "bazaar", "antiques", "vintage"], "lat": 18.9602, "lng": 72.8273,
        "fatigue_score_base": 3, "morale_score_base": 6, "best_time_of_day": "afternoon",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "The Thieves Market of Mumbai, offering old vinyl records, antique brassware, and Bollywood posters.",
        "opening_hours": ["Saturday-Thursday: 11:00-19:30"], "skip_if": "Fridays (when the main market is closed, replaced by a morning flea market).",
        "insider_tip": "Check the authenticity of antique metal carefully. Do not pay more than 50% of the initial quote.",
        "confidence_pct": 92
    },
    {
        "activity_id": "mani_bhavan_mumbai_19", "destination": "Mumbai", "name": "Mani Bhavan Gandhi Museum",
        "category": "cultural", "duration_minutes": 60, "cost_per_person": 20,
        "available_slots": ["09:30", "12:00", "14:30", "16:00"], "risk_level": "low",
        "tags": ["museum", "history", "gandhi", "heritage"], "lat": 18.9599, "lng": 72.8112,
        "fatigue_score_base": 2, "morale_score_base": 8, "best_time_of_day": "morning",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "A peaceful heritage building that served as Mahatma Gandhi's Mumbai headquarters from 1917 to 1934.",
        "opening_hours": ["Monday-Sunday: 09:30-18:00"], "skip_if": "None; a quick, informative stop near Girgaon Chowpatty.",
        "insider_tip": "View the detailed miniature hand-crafted dioramas depicting key events in Gandhi's life on the second floor.",
        "confidence_pct": 98
    },
    {
        "activity_id": "sanjay_cycle_mumbai_20", "destination": "Mumbai", "name": "Bandra Bandstand Coastal Walk",
        "category": "nature", "duration_minutes": 60, "cost_per_person": 0,
        "available_slots": ["08:00", "16:30", "18:00"], "risk_level": "low",
        "tags": ["promenade", "coast", "scenic", "relaxed"], "lat": 19.0430, "lng": 72.8190,
        "fatigue_score_base": 2, "morale_score_base": 7, "best_time_of_day": "evening",
        "best_season": ["Oct-Mar"], "accessibility": "easy",
        "editorial_summary": "A rocky coastal promenade in Bandra, home to Bollywood superstar bungalows and ocean breezes.",
        "opening_hours": ["Monday-Sunday: 24 Hours"], "skip_if": "Extremely stormy seas.",
        "insider_tip": "Look for the Bollywood 'Walk of Stars' featuring brass handprints of famous actors in the pavement.",
        "confidence_pct": 97
    }
]
